/**
 * Texte der Sprach-Landingpages. EINE Datei für alle Sprachen.
 *
 * Reihenfolge = Reihenfolge im Sprachwähler: grob nach Größe der
 * Sprachgemeinschaft in Deutschland, damit die häufigsten oben stehen.
 *
 * ACHTUNG: Die Übersetzungen stammen von Claude. Für die großen Sprachen
 * (tr, ar, ru, uk, pl, ro, en) sind sie belastbar; bei den selteneren
 * (ti, so, ps, ku) sollte vor größerer Werbung jemand mit Muttersprache
 * gegenlesen. Fehler hier stehen öffentlich auf der Seite.
 */

const SPRACHEN = [
  { code: 'tr', eigenname: 'Türkçe' },
  { code: 'ar', eigenname: 'العربية', rtl: true },
  { code: 'ru', eigenname: 'Русский' },
  { code: 'uk', eigenname: 'Українська' },
  { code: 'pl', eigenname: 'Polski' },
  { code: 'ro', eigenname: 'Română' },
  { code: 'en', eigenname: 'English' },
  { code: 'fa', eigenname: 'فارسی', rtl: true },
  { code: 'ku', eigenname: 'Kurdî' },
  { code: 'bg', eigenname: 'Български' },
  { code: 'hr', eigenname: 'Hrvatski' },
  { code: 'sr', eigenname: 'Српски' },
  { code: 'bs', eigenname: 'Bosanski' },
  { code: 'sq', eigenname: 'Shqip' },
  { code: 'it', eigenname: 'Italiano' },
  { code: 'el', eigenname: 'Ελληνικά' },
  { code: 'es', eigenname: 'Español' },
  { code: 'pt', eigenname: 'Português' },
  { code: 'fr', eigenname: 'Français' },
  { code: 'hu', eigenname: 'Magyar' },
  { code: 'vi', eigenname: 'Tiếng Việt' },
  { code: 'hi', eigenname: 'हिन्दी' },
  { code: 'ur', eigenname: 'اردو', rtl: true },
  { code: 'ps', eigenname: 'پښتو', rtl: true },
  { code: 'ti', eigenname: 'ትግርኛ' },
  { code: 'so', eigenname: 'Soomaali' },
  { code: 'zh', eigenname: '中文' },
];

const TEXTE = {};

TEXTE.tr = {
  s4Titel: "Sık sorulan sorular",
  faq: [
    { f: "Ücreti ne kadar?", a: "İlk 3 mektup ücretsiz (bekleme listesi koduyla 5). Sonrasında kontör satın alırsınız: 5 analiz 2,99 €, 15 analiz 6,99 €. Abonelik yok, hesap açmak yok." },
    { f: "Hangi mektupları açıklayabilir?", a: "İş ve İşçi Bulma Kurumu (Jobcenter), Yabancılar Dairesi, emeklilik kurumu, hastalık sigortası, aile kasası (Kindergeld), vergi dairesi veya ceza dairesinden gelen mektuplar — kısacası hemen hemen her resmî mektup." },
    { f: "Verilerime ne oluyor?", a: "Mektuplarınız şifreli olarak kendi cihazınızda kalır. Analiz için fotoğraf bir kez güvenli şekilde yapay zekâya gönderilir ve orada en geç 30 gün sonra silinir. Hesap açmanız gerekmez." },
  ],
  locale: 'tr_TR', navLabel: 'Dil seçin',
  titel: 'BehördenKlar – Alman resmî mektuplarını anlayın',
  beschreibung: 'BehördenKlar Alman resmî mektuplarını basit kelimelerle — Türkçe — açıklar. Fotoğraf çekin, anlayın, doğru cevap verin.',
  ogTitel: 'Alman resmî mektubu mu geldi?',
  ogBeschreibung: 'Fotoğraf çekin – BehördenKlar mektupları basit bir dille, Türkçe açıklar. Bekleme listesi: 5 ücretsiz analiz.',
  h1a: 'Alman dairesinden mektup mu geldi?', h1b: 'Artık anlamak kolay.',
  intro: 'Mektubun fotoğrafını çekin. BehördenKlar mektubu basit kelimelerle — <strong>ve Türkçe olarak</strong> — açıklar. Bütün süreler ve yapılacaklar listesi ile birlikte.',
  ctaHero: 'Bekleme listesine katıl', stempel: "Yakında iPhone'da",
  s1Titel: 'Dönüşüm', vorherLabel: 'Önce · Orijinal mektup (Almanca)', pfeil: 'bir fotoğraf sonra',
  nachherLabel: 'Sonra · BehördenKlar Türkçe',
  nachherText: 'Geçerli bir neden olmadan randevuya gitmezseniz, bir ay boyunca %10 daha az para alırsınız. Randevuya gidin — veya zamanında iptal edin.',
  hinweis: 'Uygulama mektupları basit Almanca ile açıklar ve 25’ten fazla dile çevirir.',
  s2Titel: 'Nasıl çalışır',
  schritt1T: 'Fotoğraf çekin', schritt1B: 'Mektubun fotoğrafını çekin — veya PDF yükleyin.',
  schritt2T: 'Anlayın', schritt2B: 'Basit kelimeler, kendi dilinizde. Bir lamba işin ne kadar acil olduğunu gösterir.',
  schritt3T: 'Doğru cevap verin', schritt3B: 'Yapılacaklar listesi, süre hatırlatması ve hazır bir cevap.',
  s3Titel: 'Erken erişim', formularKopf: 'Form F-01 · Bekleme listesi', formH3: 'İlk kullananlardan olun',
  formText: 'Uygulama yakında iPhone için geliyor. Şimdi kaydolun — uygulama hazır olunca size <strong>bir</strong> e-posta göndeririz. Reklam yok.',
  bonus: '<strong>Hediyeniz:</strong> 3 yerine <strong>5 mektubu ücretsiz</strong> analiz edin. Kodu e-posta ile alırsınız.',
  emailPlatzhalter: 'E-posta adresiniz', ctaForm: 'Bekleme listesine katıl',
  klein: 'E-posta adresinizi sadece bu bir mesaj için saklarız. İstediğiniz zaman listeden çıkabilirsiniz.',
  datenschutz: 'Gizlilik politikası (Almanca)', impressum: 'Impressum (Almanca)', fussFrage: 'Sorunuz mu var?',
};

TEXTE.ar = {
  s4Titel: "الأسئلة الشائعة",
  faq: [
    { f: "كم التكلفة؟", a: "أول 3 رسائل مجاناً (5 مع رمز قائمة الانتظار). بعد ذلك تشتري رصيداً: 5 تحليلات بـ 2,99 يورو أو 15 بـ 6,99 يورو. بدون اشتراك وبدون حساب." },
    { f: "أي الرسائل يمكن شرحها؟", a: "رسائل من مركز العمل (Jobcenter)، دائرة الأجانب، التأمين التقاعدي، التأمين الصحي، صندوق الأسرة (Kindergeld)، مكتب الضرائب أو دائرة المخالفات — باختصار: تقريباً كل رسالة رسمية." },
    { f: "ماذا يحدث لبياناتي؟", a: "تبقى رسائلك مشفّرة على جهازك. للتحليل تُرسل الصورة مرة واحدة بشكل آمن إلى الذكاء الاصطناعي وتُحذف هناك خلال 30 يوماً كحد أقصى. لا تحتاج إلى حساب." },
  ],
  locale: 'ar_AR', navLabel: 'اختر اللغة',
  titel: 'BehördenKlar – افهم الرسائل الرسمية الألمانية',
  beschreibung: 'يشرح BehördenKlar الرسائل الرسمية الألمانية بكلمات بسيطة — بالعربية. صوّر الرسالة، افهمها، وردّ بشكل صحيح.',
  ogTitel: 'وصلتك رسالة من دائرة ألمانية؟',
  ogBeschreibung: 'صوّر الرسالة – يشرحها BehördenKlar بلغة بسيطة وبالعربية. قائمة الانتظار: 5 تحليلات مجانية.',
  h1a: 'وصلتك رسالة من دائرة ألمانية؟', h1b: 'الآن تفهمها بسهولة.',
  intro: 'صوّر الرسالة. يشرحها BehördenKlar بكلمات بسيطة — <strong>وبالعربية</strong> — مع كل المواعيد النهائية وقائمة بما عليك فعله.',
  ctaHero: 'انضم إلى قائمة الانتظار', stempel: 'قريباً على iPhone',
  s1Titel: 'قبل وبعد', vorherLabel: 'قبل · الرسالة الأصلية (بالألمانية)', pfeil: 'بعد صورة واحدة',
  nachherLabel: 'بعد · BehördenKlar بالعربية',
  nachherText: 'إذا لم تحضر الموعد بدون سبب وجيه، ستحصل على مال أقل بنسبة 10٪ لمدة شهر. اذهب إلى الموعد — أو ألغِه في الوقت المناسب.',
  hinweis: 'يشرح التطبيق الرسائل بألمانية بسيطة ويترجمها إلى أكثر من 25 لغة.',
  s2Titel: 'كيف يعمل',
  schritt1T: 'صوّر', schritt1B: 'صوّر الرسالة — أو ارفع ملف PDF.',
  schritt2T: 'افهم', schritt2B: 'كلمات بسيطة بلغتك. وإشارة ملوّنة تبيّن مدى الاستعجال.',
  schritt3T: 'ردّ بشكل صحيح', schritt3B: 'قائمة مهام، تذكير بالموعد النهائي، ومسودة ردّ جاهزة.',
  s3Titel: 'وصول مبكر', formularKopf: 'استمارة F-01 · قائمة الانتظار', formH3: 'كن من الأوائل',
  formText: 'التطبيق قادم قريباً لـ iPhone. سجّل الآن — سنرسل لك <strong>رسالة واحدة</strong> عند الإطلاق. بدون إعلانات.',
  bonus: '<strong>هديتك:</strong> حلّل <strong>5 رسائل مجاناً</strong> بدلاً من 3. ستصلك الشيفرة بالبريد.',
  emailPlatzhalter: 'بريدك الإلكتروني', ctaForm: 'انضم إلى قائمة الانتظار',
  klein: 'نحفظ بريدك لهذه الرسالة الواحدة فقط. يمكنك إلغاء الاشتراك في أي وقت.',
  datenschutz: 'سياسة الخصوصية (بالألمانية)', impressum: 'بيانات الناشر (بالألمانية)', fussFrage: 'لديك سؤال؟',
};

TEXTE.ru = {
  s4Titel: "Частые вопросы",
  faq: [
    { f: "Сколько это стоит?", a: "Первые 3 письма бесплатно (5 с кодом из списка ожидания). Дальше вы покупаете баланс: 5 разборов за 2,99 €, 15 за 6,99 €. Без подписки и без учётной записи." },
    { f: "Какие письма приложение объясняет?", a: "Письма из джобцентра, ведомства по делам иностранцев, пенсионного страхования, больничной кассы, семейной кассы (Kindergeld), налоговой или органа по штрафам — словом, почти любое официальное письмо." },
    { f: "Что происходит с моими данными?", a: "Ваши письма остаются зашифрованными на вашем устройстве. Для разбора фото один раз безопасно отправляется ИИ и удаляется там не позднее чем через 30 дней. Учётная запись не нужна." },
  ],
  locale: 'ru_RU', navLabel: 'Выберите язык',
  titel: 'BehördenKlar – понять письмо из немецкого ведомства',
  beschreibung: 'BehördenKlar объясняет письма из немецких ведомств простыми словами — по-русски. Сфотографируйте, поймите, ответьте правильно.',
  ogTitel: 'Пришло письмо из ведомства?',
  ogBeschreibung: 'Сфотографируйте — BehördenKlar объяснит письмо простым языком, по-русски. В списке ожидания: 5 бесплатных разборов.',
  h1a: 'Письмо из немецкого ведомства?', h1b: 'Наконец-то понятно.',
  intro: 'Сфотографируйте письмо. BehördenKlar объяснит его простыми словами — <strong>и по-русски</strong>. Со всеми сроками и списком дел.',
  ctaHero: 'В список ожидания', stempel: 'Скоро в App Store',
  s1Titel: 'До и после', vorherLabel: 'До · Оригинал (по-немецки)', pfeil: 'одно фото спустя',
  nachherLabel: 'После · BehördenKlar по-русски',
  nachherText: 'Если вы без уважительной причины не придёте на приём, целый месяц будете получать на 10 % меньше денег. Придите — или вовремя отмените.',
  hinweis: 'Приложение объясняет письма простым немецким и переводит более чем на 25 языков.',
  s2Titel: 'Как это работает',
  schritt1T: 'Сфотографируйте', schritt1B: 'Сфотографируйте письмо — или загрузите PDF.',
  schritt2T: 'Поймите', schritt2B: 'Простые слова на вашем языке. Светофор показывает, насколько это срочно.',
  schritt3T: 'Ответьте правильно', schritt3B: 'Список дел, напоминание о сроке и готовый черновик ответа.',
  s3Titel: 'Ранний доступ', formularKopf: 'Форма F-01 · Список ожидания', formH3: 'Будьте среди первых',
  formText: 'Приложение скоро выйдет для iPhone. Запишитесь — мы напишем <strong>одно</strong> письмо, когда всё будет готово. Без рекламы.',
  bonus: '<strong>Ваш подарок:</strong> <strong>5 писем бесплатно</strong> вместо 3. Код придёт по электронной почте.',
  emailPlatzhalter: 'Ваш адрес электронной почты', ctaForm: 'Записаться в список',
  klein: 'Мы сохраним адрес только для этого одного письма. Отписаться можно в любой момент.',
  datenschutz: 'Политика конфиденциальности (по-немецки)', impressum: 'Выходные данные (по-немецки)', fussFrage: 'Есть вопросы?',
};

TEXTE.uk = {
  s4Titel: "Часті запитання",
  faq: [
    { f: "Скільки це коштує?", a: "Перші 3 листи безкоштовно (5 з кодом зі списку очікування). Далі ви купуєте баланс: 5 аналізів за 2,99 €, 15 за 6,99 €. Без підписки й без облікового запису." },
    { f: "Які листи застосунок пояснює?", a: "Листи з джобцентру, відомства у справах іноземців, пенсійного страхування, лікарняної каси, сімейної каси (Kindergeld), податкової або органу зі штрафів — словом, майже будь-який офіційний лист." },
    { f: "Що відбувається з моїми даними?", a: "Ваші листи залишаються зашифрованими на вашому пристрої. Для аналізу фото один раз безпечно надсилається до ШІ і видаляється там щонайпізніше через 30 днів. Обліковий запис не потрібен." },
  ],
  locale: 'uk_UA', navLabel: 'Оберіть мову',
  titel: 'BehördenKlar – зрозуміти лист із німецької установи',
  beschreibung: 'BehördenKlar пояснює листи з німецьких установ простими словами — українською. Сфотографуйте, зрозумійте, відповідайте правильно.',
  ogTitel: 'Прийшов лист з установи?',
  ogBeschreibung: 'Сфотографуйте — BehördenKlar пояснить лист простою мовою, українською. У списку очікування: 5 безкоштовних аналізів.',
  h1a: 'Лист із німецької установи?', h1b: 'Нарешті зрозуміло.',
  intro: 'Сфотографуйте лист. BehördenKlar пояснить його простими словами — <strong>і українською</strong>. З усіма термінами та списком справ.',
  ctaHero: 'До списку очікування', stempel: 'Скоро в App Store',
  s1Titel: 'До і після', vorherLabel: 'До · Оригінал (німецькою)', pfeil: 'одне фото потому',
  nachherLabel: 'Після · BehördenKlar українською',
  nachherText: 'Якщо ви без поважної причини не прийдете на зустріч, цілий місяць отримуватимете на 10 % менше грошей. Прийдіть — або вчасно скасуйте.',
  hinweis: 'Застосунок пояснює листи простою німецькою та перекладає більш ніж 25 мовами.',
  s2Titel: 'Як це працює',
  schritt1T: 'Сфотографуйте', schritt1B: 'Сфотографуйте лист — або завантажте PDF.',
  schritt2T: 'Зрозумійте', schritt2B: 'Прості слова вашою мовою. Світлофор показує, наскільки це терміново.',
  schritt3T: 'Відповідайте правильно', schritt3B: 'Список справ, нагадування про термін і готовий чернетковий лист.',
  s3Titel: 'Ранній доступ', formularKopf: 'Форма F-01 · Список очікування', formH3: 'Будьте серед перших',
  formText: 'Застосунок скоро вийде для iPhone. Запишіться — ми надішлемо <strong>один</strong> лист, коли все буде готово. Без реклами.',
  bonus: '<strong>Ваш подарунок:</strong> <strong>5 листів безкоштовно</strong> замість 3. Код надійде на пошту.',
  emailPlatzhalter: 'Ваша електронна адреса', ctaForm: 'Записатися до списку',
  klein: 'Ми збережемо адресу лише для цього одного листа. Відписатися можна будь-коли.',
  datenschutz: 'Політика конфіденційності (німецькою)', impressum: 'Вихідні дані (німецькою)', fussFrage: 'Маєте питання?',
};

TEXTE.pl = {
  s4Titel: "Częste pytania",
  faq: [
    { f: "Ile to kosztuje?", a: "Pierwsze 3 pisma za darmo (5 z kodem z listy oczekujących). Potem kupujesz doładowanie: 5 analiz za 2,99 €, 15 za 6,99 €. Bez abonamentu i bez konta." },
    { f: "Jakie pisma aplikacja wyjaśnia?", a: "Pisma z Jobcenter, urzędu do spraw cudzoziemców, ubezpieczenia emerytalnego, kasy chorych, kasy rodzinnej (Kindergeld), urzędu skarbowego lub organu mandatowego — krótko mówiąc prawie każde oficjalne pismo." },
    { f: "Co dzieje się z moimi danymi?", a: "Twoje pisma pozostają zaszyfrowane na Twoim urządzeniu. Do analizy zdjęcie jest raz bezpiecznie wysyłane do SI i usuwane tam najpóźniej po 30 dniach. Konto nie jest potrzebne." },
  ],
  locale: 'pl_PL', navLabel: 'Wybierz język',
  titel: 'BehördenKlar – zrozum pismo z niemieckiego urzędu',
  beschreibung: 'BehördenKlar wyjaśnia pisma z niemieckich urzędów prostymi słowami — po polsku. Zrób zdjęcie, zrozum, odpowiedz poprawnie.',
  ogTitel: 'Przyszło pismo z urzędu?',
  ogBeschreibung: 'Zrób zdjęcie — BehördenKlar wyjaśni pismo prostym językiem, po polsku. Lista oczekujących: 5 darmowych analiz.',
  h1a: 'Pismo z niemieckiego urzędu?', h1b: 'Wreszcie zrozumiałe.',
  intro: 'Zrób zdjęcie pisma. BehördenKlar wyjaśni je prostymi słowami — <strong>i po polsku</strong>. Ze wszystkimi terminami i listą zadań.',
  ctaHero: 'Na listę oczekujących', stempel: 'Wkrótce w App Store',
  s1Titel: 'Przed i po', vorherLabel: 'Przed · Oryginał (po niemiecku)', pfeil: 'jedno zdjęcie później',
  nachherLabel: 'Po · BehördenKlar po polsku',
  nachherText: 'Jeśli bez ważnego powodu nie przyjdziesz na spotkanie, przez miesiąc dostaniesz o 10 % mniej pieniędzy. Przyjdź — albo odwołaj w porę.',
  hinweis: 'Aplikacja wyjaśnia pisma prostym niemieckim i tłumaczy na ponad 25 języków.',
  s2Titel: 'Jak to działa',
  schritt1T: 'Zrób zdjęcie', schritt1B: 'Sfotografuj pismo — albo wgraj PDF.',
  schritt2T: 'Zrozum', schritt2B: 'Proste słowa w Twoim języku. Sygnalizacja pokazuje, jak pilne to jest.',
  schritt3T: 'Odpowiedz poprawnie', schritt3B: 'Lista zadań, przypomnienie o terminie i gotowy szkic odpowiedzi.',
  s3Titel: 'Wcześniejszy dostęp', formularKopf: 'Formularz F-01 · Lista oczekujących', formH3: 'Bądź wśród pierwszych',
  formText: 'Aplikacja wkrótce na iPhone. Zapisz się — wyślemy <strong>jedną</strong> wiadomość, gdy będzie gotowa. Bez reklam.',
  bonus: '<strong>Twój prezent:</strong> <strong>5 pism za darmo</strong> zamiast 3. Kod dostaniesz mailem.',
  emailPlatzhalter: 'Twój adres e-mail', ctaForm: 'Zapisz się na listę',
  klein: 'Zapiszemy adres tylko dla tej jednej wiadomości. W każdej chwili możesz się wypisać.',
  datenschutz: 'Polityka prywatności (po niemiecku)', impressum: 'Impressum (po niemiecku)', fussFrage: 'Masz pytania?',
};

TEXTE.ro = {
  s4Titel: "Întrebări frecvente",
  faq: [
    { f: "Cât costă?", a: "Primele 3 scrisori sunt gratuite (5 cu codul din lista de așteptare). Apoi cumperi credit: 5 analize la 2,99 €, 15 la 6,99 €. Fără abonament și fără cont." },
    { f: "Ce scrisori poate explica aplicația?", a: "Scrisori de la Jobcenter, Oficiul pentru Străini, asigurarea de pensie, casa de sănătate, casa familială (Kindergeld), administrația fiscală sau oficiul de amenzi — pe scurt, aproape orice scrisoare oficială." },
    { f: "Ce se întâmplă cu datele mele?", a: "Scrisorile tale rămân criptate pe dispozitivul tău. Pentru analiză, fotografia este trimisă o singură dată în siguranță către IA și este ștearsă acolo în cel mult 30 de zile. Nu ai nevoie de cont." },
  ],
  locale: 'ro_RO', navLabel: 'Alege limba',
  titel: 'BehördenKlar – înțelege scrisoarea de la autoritățile germane',
  beschreibung: 'BehördenKlar explică scrisorile oficiale germane în cuvinte simple — în română. Fă o poză, înțelege, răspunde corect.',
  ogTitel: 'Ai primit o scrisoare de la autorități?',
  ogBeschreibung: 'Fă o poză — BehördenKlar explică scrisoarea pe înțelesul tuturor, în română. Listă de așteptare: 5 analize gratuite.',
  h1a: 'Scrisoare de la o autoritate germană?', h1b: 'Acum se înțelege.',
  intro: 'Fotografiază scrisoarea. BehördenKlar o explică în cuvinte simple — <strong>și în română</strong>. Cu toate termenele și o listă de pași.',
  ctaHero: 'Pe lista de așteptare', stempel: 'În curând pe iPhone',
  s1Titel: 'Înainte și după', vorherLabel: 'Înainte · Original (în germană)', pfeil: 'o poză mai târziu',
  nachherLabel: 'După · BehördenKlar în română',
  nachherText: 'Dacă nu vii la programare fără un motiv întemeiat, timp de o lună primești cu 10 % mai puțini bani. Mergi — sau anulează din timp.',
  hinweis: 'Aplicația explică scrisorile în germană simplă și le traduce în peste 25 de limbi.',
  s2Titel: 'Cum funcționează',
  schritt1T: 'Fă o poză', schritt1B: 'Fotografiază scrisoarea — sau încarcă un PDF.',
  schritt2T: 'Înțelege', schritt2B: 'Cuvinte simple, în limba ta. Un semafor arată cât de urgent este.',
  schritt3T: 'Răspunde corect', schritt3B: 'Listă de pași, memento pentru termen și o ciornă de răspuns gata făcută.',
  s3Titel: 'Acces timpuriu', formularKopf: 'Formular F-01 · Listă de așteptare', formH3: 'Fii printre primii',
  formText: 'Aplicația vine în curând pentru iPhone. Înscrie-te — îți trimitem <strong>un singur</strong> e-mail la lansare. Fără reclame.',
  bonus: '<strong>Cadoul tău:</strong> <strong>5 scrisori gratuit</strong> în loc de 3. Primești codul pe e-mail.',
  emailPlatzhalter: 'Adresa ta de e-mail', ctaForm: 'Înscrie-te pe listă',
  klein: 'Păstrăm adresa doar pentru acest singur mesaj. Te poți dezabona oricând.',
  datenschutz: 'Politica de confidențialitate (în germană)', impressum: 'Impressum (în germană)', fussFrage: 'Ai întrebări?',
};

TEXTE.en = {
  s4Titel: "Frequently asked questions",
  faq: [
    { f: "What does it cost?", a: "Your first 3 letters are free (5 with the waiting-list code). After that you buy credit: 5 analyses for €2.99 or 15 for €6.99. No subscription, no account." },
    { f: "Which letters can the app explain?", a: "Letters from the Jobcenter, the immigration office, pension insurance, health insurance, the family benefits office (Kindergeld), the tax office or the fines authority — in short, almost any official letter." },
    { f: "What happens to my data?", a: "Your letters stay encrypted on your own device. For the analysis the photo is sent once, securely, to the AI and is deleted there after 30 days at the latest. You do not need an account." },
  ],
  locale: 'en_US', navLabel: 'Choose language',
  titel: 'BehördenKlar – understand letters from German authorities',
  beschreibung: 'BehördenKlar explains German official letters in plain words — in English. Take a photo, understand it, respond correctly.',
  ogTitel: 'Got a letter from a German authority?',
  ogBeschreibung: 'Take a photo — BehördenKlar explains the letter in plain language, in English. Waiting list: 5 free analyses.',
  h1a: 'A letter from a German authority?', h1b: 'Finally clear.',
  intro: 'Take a photo of the letter. BehördenKlar explains it in plain words — <strong>and in English</strong>. With every deadline and a to-do list.',
  ctaHero: 'Join the waiting list', stempel: 'Coming soon on iPhone',
  s1Titel: 'Before and after', vorherLabel: 'Before · Original letter (German)', pfeil: 'one photo later',
  nachherLabel: 'After · BehördenKlar in English',
  nachherText: 'If you miss the appointment without a good reason, you will get 10% less money for one month. Go — or cancel in good time.',
  hinweis: 'The app explains letters in plain German and translates them into more than 25 languages.',
  s2Titel: 'How it works',
  schritt1T: 'Take a photo', schritt1B: 'Photograph the letter — or upload a PDF.',
  schritt2T: 'Understand', schritt2B: 'Plain words, in your language. A traffic light shows how urgent it is.',
  schritt3T: 'Respond correctly', schritt3B: 'A to-do list, a deadline reminder and a ready-made draft reply.',
  s3Titel: 'Early access', formularKopf: 'Form F-01 · Waiting list', formH3: 'Be among the first',
  formText: 'The app is coming soon for iPhone. Sign up — we will send you <strong>one</strong> email when it launches. No advertising.',
  bonus: '<strong>Your gift:</strong> analyse <strong>5 letters free</strong> instead of 3. You get the code by email.',
  emailPlatzhalter: 'Your email address', ctaForm: 'Join the waiting list',
  klein: 'We store your address only for this single message. You can unsubscribe at any time.',
  datenschutz: 'Privacy policy (German)', impressum: 'Legal notice (German)', fussFrage: 'Questions?',
};

TEXTE.fa = {
  s4Titel: "پرسش‌های پرتکرار",
  faq: [
    { f: "هزینه آن چقدر است؟", a: "سه نامه اول رایگان است (با کد فهرست انتظار ۵ نامه). پس از آن اعتبار می‌خرید: ۵ تحلیل با ۲٫۹۹ یورو یا ۱۵ تحلیل با ۶٫۹۹ یورو. بدون اشتراک و بدون حساب کاربری." },
    { f: "چه نامه‌هایی را می‌تواند توضیح دهد؟", a: "نامه‌های مرکز کاریابی (Jobcenter)، اداره اتباع خارجی، بیمه بازنشستگی، بیمه درمانی، صندوق خانواده (Kindergeld)، اداره مالیات یا اداره جرایم — به‌طور خلاصه تقریباً هر نامه رسمی." },
    { f: "با اطلاعات من چه می‌شود؟", a: "نامه‌های شما رمزگذاری‌شده روی دستگاه خودتان می‌مانند. برای تحلیل، عکس یک بار به‌صورت امن به هوش مصنوعی فرستاده می‌شود و حداکثر پس از ۳۰ روز آنجا پاک می‌شود. به حساب کاربری نیاز ندارید." },
  ],
  locale: 'fa_IR', navLabel: 'زبان را انتخاب کنید',
  titel: 'BehördenKlar – نامه‌های اداری آلمان را بفهمید',
  beschreibung: 'BehördenKlar نامه‌های اداری آلمان را با کلمات ساده — به فارسی — توضیح می‌دهد. عکس بگیرید، بفهمید، درست پاسخ دهید.',
  ogTitel: 'نامه‌ای از اداره آلمانی گرفته‌اید؟',
  ogBeschreibung: 'عکس بگیرید – BehördenKlar نامه را به زبان ساده و به فارسی توضیح می‌دهد. فهرست انتظار: ۵ تحلیل رایگان.',
  h1a: 'نامه‌ای از یک اداره آلمانی؟', h1b: 'حالا قابل فهم است.',
  intro: 'از نامه عکس بگیرید. BehördenKlar آن را با کلمات ساده — <strong>و به فارسی</strong> — توضیح می‌دهد. با همه مهلت‌ها و فهرست کارها.',
  ctaHero: 'به فهرست انتظار بپیوندید', stempel: 'به‌زودی روی iPhone',
  s1Titel: 'قبل و بعد', vorherLabel: 'قبل · نامه اصلی (آلمانی)', pfeil: 'یک عکس بعد',
  nachherLabel: 'بعد · BehördenKlar به فارسی',
  nachherText: 'اگر بدون دلیل موجه به قرار ملاقات نروید، یک ماه ۱۰ درصد پول کمتری دریافت می‌کنید. بروید — یا به‌موقع لغو کنید.',
  hinweis: 'برنامه نامه‌ها را به آلمانی ساده توضیح می‌دهد و به بیش از ۲۵ زبان ترجمه می‌کند.',
  s2Titel: 'چگونه کار می‌کند',
  schritt1T: 'عکس بگیرید', schritt1B: 'از نامه عکس بگیرید — یا فایل PDF بارگذاری کنید.',
  schritt2T: 'بفهمید', schritt2B: 'کلمات ساده به زبان خودتان. یک چراغ راهنما فوریت کار را نشان می‌دهد.',
  schritt3T: 'درست پاسخ دهید', schritt3B: 'فهرست کارها، یادآوری مهلت و یک پیش‌نویس آماده پاسخ.',
  s3Titel: 'دسترسی زودهنگام', formularKopf: 'فرم F-01 · فهرست انتظار', formH3: 'جزو اولین‌ها باشید',
  formText: 'برنامه به‌زودی برای iPhone می‌آید. ثبت‌نام کنید — هنگام انتشار <strong>یک</strong> ایمیل برایتان می‌فرستیم. بدون تبلیغات.',
  bonus: '<strong>هدیه شما:</strong> به‌جای ۳ نامه، <strong>۵ نامه رایگان</strong> تحلیل کنید. کد را با ایمیل دریافت می‌کنید.',
  emailPlatzhalter: 'نشانی ایمیل شما', ctaForm: 'ثبت‌نام در فهرست انتظار',
  klein: 'نشانی شما را فقط برای همین یک پیام نگه می‌داریم. هر زمان می‌توانید لغو اشتراک کنید.',
  datenschutz: 'سیاست حفظ حریم خصوصی (آلمانی)', impressum: 'اطلاعات ناشر (آلمانی)', fussFrage: 'سؤالی دارید؟',
};

TEXTE.ku = {
  s4Titel: "Pirsên pir tên kirin",
  faq: [
    { f: "Ew çiqas dike?", a: "Sê nameyên pêşîn belaş in (bi koda lîsteya bendewariyê 5). Piştre tu krediyê dikirî: 5 analîz bi 2,99 €, 15 bi 6,99 €. Bê abone, bê hesab." },
    { f: "Kîjan name dikare rave bike?", a: "Nameyên ji Jobcenter, Daîreya Biyaniyan, sîgorteya teqawidiyê, sîgorteya tenduristiyê, sindoqa malbatê (Kindergeld), daîreya bacê an daîreya cezayan — bi kurtî hema hema her nameya fermî." },
    { f: "Bi daneyên min çi tê kirin?", a: "Nameyên te bi şîfre li ser amûra te dimînin. Ji bo analîzê wêne carekê bi ewlehî ji AI re tê şandin û li wir herî dereng piştî 30 rojan tê jêbirin. Tu hewceyî hesabekî nînî." },
  ],
  locale: 'ku_TR', navLabel: 'Zimên hilbijêre',
  titel: 'BehördenKlar – nameyên fermî yên Almanyayê fêm bike',
  beschreibung: 'BehördenKlar nameyên fermî yên Almanyayê bi peyvên hêsan — bi kurdî — rave dike. Wêne bikişîne, fêm bike, rast bersiv bide.',
  ogTitel: 'Nameyek ji daîreyeke Alman hat?',
  ogBeschreibung: 'Wêne bikişîne – BehördenKlar nameyê bi zimanekî hêsan û bi kurdî rave dike. Lîsteya bendewariyê: 5 analîzên belaş.',
  h1a: 'Nameyek ji daîreyeke Alman?', h1b: 'Niha tê fêmkirin.',
  intro: 'Wêneyê nameyê bikişîne. BehördenKlar wê bi peyvên hêsan — <strong>û bi kurdî</strong> — rave dike. Bi hemû demên dawî û lîsteyeke karan.',
  ctaHero: 'Beşdarî lîsteya bendewariyê bibe', stempel: 'Zû de li ser iPhone',
  s1Titel: 'Berê û piştre', vorherLabel: 'Berê · Nameya resen (bi almanî)', pfeil: 'wêneyek şûnda',
  nachherLabel: 'Piştre · BehördenKlar bi kurdî',
  nachherText: 'Eger tu bê sedemeke girîng neyê randevûyê, meha bê tu ji sedî 10 kêmtir pere werdigirî. Here — an jî di wextê xwe de betal bike.',
  hinweis: 'Sepan nameyan bi almaniya hêsan rave dike û wan wergerîne zêdetirî 25 zimanan.',
  s2Titel: 'Ew çawa dixebite',
  schritt1T: 'Wêne bikişîne', schritt1B: 'Wêneyê nameyê bikişîne — an PDF bar bike.',
  schritt2T: 'Fêm bike', schritt2B: 'Peyvên hêsan, bi zimanê te. Çirayek nîşan dide ka ew çiqas lezgîn e.',
  schritt3T: 'Rast bersiv bide', schritt3B: 'Lîsteya karan, bîranîna dema dawî û reşnivîseke amade.',
  s3Titel: 'Gihîştina zû', formularKopf: 'Form F-01 · Lîsteya bendewariyê', formH3: 'Di nav yekemînan de be',
  formText: 'Sepan zû de ji bo iPhone tê. Xwe tomar bike — dema ku amade be em <strong>yek</strong> e-name dişînin. Bê reklam.',
  bonus: '<strong>Diyariya te:</strong> li şûna 3, <strong>5 name belaş</strong> analîz bike. Kodê bi e-nameyê digirî.',
  emailPlatzhalter: 'Navnîşana te ya e-nameyê', ctaForm: 'Xwe li lîsteyê tomar bike',
  klein: 'Em navnîşana te tenê ji bo vê yek peyamê diparêzin. Tu her dem dikarî dev jê berdî.',
  datenschutz: 'Politîkaya nepenîtiyê (bi almanî)', impressum: 'Impressum (bi almanî)', fussFrage: 'Pirsên te hene?',
};

TEXTE.bg = {
  s4Titel: "Често задавани въпроси",
  faq: [
    { f: "Колко струва?", a: "Първите 3 писма са безплатни (5 с кода от списъка на чакащите). След това купувате кредит: 5 анализа за 2,99 €, 15 за 6,99 €. Без абонамент и без регистрация." },
    { f: "Кои писма може да обясни приложението?", a: "Писма от Jobcenter, службата за чужденци, пенсионното осигуряване, здравната каса, семейната каса (Kindergeld), данъчната служба или службата за глоби — накратко почти всяко официално писмо." },
    { f: "Какво става с данните ми?", a: "Писмата ви остават криптирани на вашето устройство. За анализа снимката се изпраща еднократно и защитено към ИИ и се изтрива там най-късно след 30 дни. Не ви трябва регистрация." },
  ],
  locale: 'bg_BG', navLabel: 'Изберете език',
  titel: 'BehördenKlar – разберете писмото от немска институция',
  beschreibung: 'BehördenKlar обяснява официалните немски писма с прости думи — на български. Снимайте, разберете, отговорете правилно.',
  ogTitel: 'Получихте писмо от институция?',
  ogBeschreibung: 'Снимайте — BehördenKlar обяснява писмото на прост език, на български. Списък на чакащите: 5 безплатни анализа.',
  h1a: 'Писмо от немска институция?', h1b: 'Най-накрая разбираемо.',
  intro: 'Снимайте писмото. BehördenKlar го обяснява с прости думи — <strong>и на български</strong>. С всички срокове и списък със задачи.',
  ctaHero: 'В списъка на чакащите', stempel: 'Скоро в App Store',
  s1Titel: 'Преди и след', vorherLabel: 'Преди · Оригинал (на немски)', pfeil: 'една снимка по-късно',
  nachherLabel: 'След · BehördenKlar на български',
  nachherText: 'Ако без основателна причина не отидете на срещата, цял месец ще получавате с 10 % по-малко пари. Отидете — или отменете навреме.',
  hinweis: 'Приложението обяснява писмата на прост немски и ги превежда на над 25 езика.',
  s2Titel: 'Как работи',
  schritt1T: 'Снимайте', schritt1B: 'Снимайте писмото — или качете PDF.',
  schritt2T: 'Разберете', schritt2B: 'Прости думи на вашия език. Светофар показва колко е спешно.',
  schritt3T: 'Отговорете правилно', schritt3B: 'Списък със задачи, напомняне за срока и готов проект на отговор.',
  s3Titel: 'Ранен достъп', formularKopf: 'Формуляр F-01 · Списък на чакащите', formH3: 'Бъдете сред първите',
  formText: 'Приложението идва скоро за iPhone. Запишете се — ще ви изпратим <strong>едно</strong> писмо при пускането. Без реклами.',
  bonus: '<strong>Вашият подарък:</strong> <strong>5 писма безплатно</strong> вместо 3. Кодът идва по имейл.',
  emailPlatzhalter: 'Вашият имейл адрес', ctaForm: 'Запишете се в списъка',
  klein: 'Пазим адреса само за това едно съобщение. Можете да се отпишете по всяко време.',
  datenschutz: 'Политика за поверителност (на немски)', impressum: 'Импресум (на немски)', fussFrage: 'Имате въпроси?',
};

TEXTE.hr = {
  s4Titel: "Česta pitanja",
  faq: [
    { f: "Koliko košta?", a: "Prva 3 pisma su besplatna (5 s kodom s liste čekanja). Zatim kupujete bodove: 5 analiza za 2,99 €, 15 za 6,99 €. Bez pretplate i bez računa." },
    { f: "Koja pisma aplikacija objašnjava?", a: "Pisma Jobcentra, Ureda za strance, mirovinskog osiguranja, zdravstvenog osiguranja, obiteljske blagajne (Kindergeld), porezne uprave ili ureda za kazne — ukratko, gotovo svako službeno pismo." },
    { f: "Što se događa s mojim podacima?", a: "Vaša pisma ostaju šifrirana na vašem uređaju. Za analizu se fotografija jednom sigurno šalje umjetnoj inteligenciji i ondje se briše najkasnije nakon 30 dana. Račun nije potreban." },
  ],
  locale: 'hr_HR', navLabel: 'Odaberite jezik',
  titel: 'BehördenKlar – razumite pismo njemačke ustanove',
  beschreibung: 'BehördenKlar objašnjava njemačka službena pisma jednostavnim riječima — na hrvatskom. Fotografirajte, razumijte, odgovorite ispravno.',
  ogTitel: 'Stiglo je pismo od ustanove?',
  ogBeschreibung: 'Fotografirajte — BehördenKlar objašnjava pismo jednostavnim jezikom, na hrvatskom. Lista čekanja: 5 besplatnih analiza.',
  h1a: 'Pismo njemačke ustanove?', h1b: 'Napokon razumljivo.',
  intro: 'Fotografirajte pismo. BehördenKlar ga objašnjava jednostavnim riječima — <strong>i na hrvatskom</strong>. Sa svim rokovima i popisom zadataka.',
  ctaHero: 'Na listu čekanja', stempel: 'Uskoro na iPhoneu',
  s1Titel: 'Prije i poslije', vorherLabel: 'Prije · Izvornik (na njemačkom)', pfeil: 'jednu fotografiju kasnije',
  nachherLabel: 'Poslije · BehördenKlar na hrvatskom',
  nachherText: 'Ako bez dobrog razloga ne dođete na termin, mjesec dana dobivate 10 % manje novca. Dođite — ili otkažite na vrijeme.',
  hinweis: 'Aplikacija objašnjava pisma jednostavnim njemačkim i prevodi ih na više od 25 jezika.',
  s2Titel: 'Kako radi',
  schritt1T: 'Fotografirajte', schritt1B: 'Fotografirajte pismo — ili učitajte PDF.',
  schritt2T: 'Razumijte', schritt2B: 'Jednostavne riječi na vašem jeziku. Semafor pokazuje koliko je hitno.',
  schritt3T: 'Odgovorite ispravno', schritt3B: 'Popis zadataka, podsjetnik na rok i gotov nacrt odgovora.',
  s3Titel: 'Rani pristup', formularKopf: 'Obrazac F-01 · Lista čekanja', formH3: 'Budite među prvima',
  formText: 'Aplikacija uskoro stiže za iPhone. Prijavite se — poslat ćemo <strong>jednu</strong> poruku kad krene. Bez reklama.',
  bonus: '<strong>Vaš poklon:</strong> <strong>5 pisama besplatno</strong> umjesto 3. Kod dobivate e-poštom.',
  emailPlatzhalter: 'Vaša e-mail adresa', ctaForm: 'Prijavite se na listu',
  klein: 'Adresu čuvamo samo za ovu jednu poruku. Možete se odjaviti u svakom trenutku.',
  datenschutz: 'Pravila privatnosti (na njemačkom)', impressum: 'Impressum (na njemačkom)', fussFrage: 'Imate pitanja?',
};

TEXTE.sr = {
  s4Titel: "Честа питања",
  faq: [
    { f: "Колико кошта?", a: "Прва 3 писма су бесплатна (5 са кодом са листе чекања). Затим купујете бодове: 5 анализа за 2,99 €, 15 за 6,99 €. Без претплате и без налога." },
    { f: "Која писма апликација објашњава?", a: "Писма Јобцентра, Управе за странце, пензијског осигурања, здравственог осигурања, породичне благајне (Kindergeld), пореске управе или службе за казне — укратко, готово свако службено писмо." },
    { f: "Шта се дешава са мојим подацима?", a: "Ваша писма остају шифрована на вашем уређају. За анализу се фотографија једном безбедно шаље вештачкој интелигенцији и тамо се брише најкасније после 30 дана. Налог није потребан." },
  ],
  locale: 'sr_RS', navLabel: 'Изаберите језик',
  titel: 'BehördenKlar – разумејте писмо немачке установе',
  beschreibung: 'BehördenKlar објашњава немачка службена писма једноставним речима — на српском. Фотографишите, разумејте, одговорите исправно.',
  ogTitel: 'Стигло је писмо од установе?',
  ogBeschreibung: 'Фотографишите — BehördenKlar објашњава писмо једноставним језиком, на српском. Листа чекања: 5 бесплатних анализа.',
  h1a: 'Писмо немачке установе?', h1b: 'Коначно разумљиво.',
  intro: 'Фотографишите писмо. BehördenKlar га објашњава једноставним речима — <strong>и на српском</strong>. Са свим роковима и списком задатака.',
  ctaHero: 'На листу чекања', stempel: 'Ускоро на iPhone-у',
  s1Titel: 'Пре и после', vorherLabel: 'Пре · Оригинал (на немачком)', pfeil: 'једну фотографију касније',
  nachherLabel: 'После · BehördenKlar на српском',
  nachherText: 'Ако без доброг разлога не дођете на термин, месец дана добијате 10 % мање новца. Дођите — или откажите на време.',
  hinweis: 'Апликација објашњава писма једноставним немачким и преводи их на више од 25 језика.',
  s2Titel: 'Како ради',
  schritt1T: 'Фотографишите', schritt1B: 'Фотографишите писмо — или отпремите PDF.',
  schritt2T: 'Разумејте', schritt2B: 'Једноставне речи на вашем језику. Семафор показује колико је хитно.',
  schritt3T: 'Одговорите исправно', schritt3B: 'Списак задатака, подсетник на рок и готов нацрт одговора.',
  s3Titel: 'Рани приступ', formularKopf: 'Образац F-01 · Листа чекања', formH3: 'Будите међу првима',
  formText: 'Апликација ускоро стиже за iPhone. Пријавите се — послаћемо <strong>једну</strong> поруку када крене. Без реклама.',
  bonus: '<strong>Ваш поклон:</strong> <strong>5 писама бесплатно</strong> уместо 3. Код добијате мејлом.',
  emailPlatzhalter: 'Ваша имејл адреса', ctaForm: 'Пријавите се на листу',
  klein: 'Адресу чувамо само за ову једну поруку. Можете се одјавити у сваком тренутку.',
  datenschutz: 'Политика приватности (на немачком)', impressum: 'Импресум (на немачком)', fussFrage: 'Имате питања?',
};

TEXTE.bs = {
  s4Titel: "Česta pitanja",
  faq: [
    { f: "Koliko košta?", a: "Prva 3 pisma su besplatna (5 s kodom s liste čekanja). Zatim kupujete bodove: 5 analiza za 2,99 €, 15 za 6,99 €. Bez pretplate i bez računa." },
    { f: "Koja pisma aplikacija objašnjava?", a: "Pisma Jobcentra, Ureda za strance, penzionog osiguranja, zdravstvenog osiguranja, porodične blagajne (Kindergeld), poreske uprave ili ureda za kazne — ukratko, gotovo svako službeno pismo." },
    { f: "Šta se dešava s mojim podacima?", a: "Vaša pisma ostaju šifrirana na vašem uređaju. Za analizu se fotografija jednom sigurno šalje vještačkoj inteligenciji i tamo se briše najkasnije nakon 30 dana. Račun nije potreban." },
  ],
  locale: 'bs_BA', navLabel: 'Odaberite jezik',
  titel: 'BehördenKlar – razumijte pismo njemačke ustanove',
  beschreibung: 'BehördenKlar objašnjava njemačka službena pisma jednostavnim riječima — na bosanskom. Fotografišite, razumijte, odgovorite ispravno.',
  ogTitel: 'Stiglo je pismo od ustanove?',
  ogBeschreibung: 'Fotografišite — BehördenKlar objašnjava pismo jednostavnim jezikom, na bosanskom. Lista čekanja: 5 besplatnih analiza.',
  h1a: 'Pismo njemačke ustanove?', h1b: 'Konačno razumljivo.',
  intro: 'Fotografišite pismo. BehördenKlar ga objašnjava jednostavnim riječima — <strong>i na bosanskom</strong>. Sa svim rokovima i spiskom zadataka.',
  ctaHero: 'Na listu čekanja', stempel: 'Uskoro na iPhoneu',
  s1Titel: 'Prije i poslije', vorherLabel: 'Prije · Original (na njemačkom)', pfeil: 'jednu fotografiju kasnije',
  nachherLabel: 'Poslije · BehördenKlar na bosanskom',
  nachherText: 'Ako bez dobrog razloga ne dođete na termin, mjesec dana dobijate 10 % manje novca. Dođite — ili otkažite na vrijeme.',
  hinweis: 'Aplikacija objašnjava pisma jednostavnim njemačkim i prevodi ih na više od 25 jezika.',
  s2Titel: 'Kako radi',
  schritt1T: 'Fotografišite', schritt1B: 'Fotografišite pismo — ili učitajte PDF.',
  schritt2T: 'Razumijte', schritt2B: 'Jednostavne riječi na vašem jeziku. Semafor pokazuje koliko je hitno.',
  schritt3T: 'Odgovorite ispravno', schritt3B: 'Spisak zadataka, podsjetnik na rok i gotov nacrt odgovora.',
  s3Titel: 'Rani pristup', formularKopf: 'Obrazac F-01 · Lista čekanja', formH3: 'Budite među prvima',
  formText: 'Aplikacija uskoro stiže za iPhone. Prijavite se — poslat ćemo <strong>jednu</strong> poruku kad krene. Bez reklama.',
  bonus: '<strong>Vaš poklon:</strong> <strong>5 pisama besplatno</strong> umjesto 3. Kod dobijate e-poštom.',
  emailPlatzhalter: 'Vaša e-mail adresa', ctaForm: 'Prijavite se na listu',
  klein: 'Adresu čuvamo samo za ovu jednu poruku. Možete se odjaviti u svakom trenutku.',
  datenschutz: 'Pravila privatnosti (na njemačkom)', impressum: 'Impressum (na njemačkom)', fussFrage: 'Imate pitanja?',
};

TEXTE.sq = {
  s4Titel: "Pyetje të shpeshta",
  faq: [
    { f: "Sa kushton?", a: "3 letrat e para janë falas (5 me kodin e listës së pritjes). Më pas blini kredi: 5 analiza për 2,99 €, 15 për 6,99 €. Pa abonim dhe pa llogari." },
    { f: "Cilat letra mund të shpjegojë?", a: "Letra nga Jobcenter, Zyra e të Huajve, sigurimi i pensionit, sigurimi shëndetësor, arka familjare (Kindergeld), zyra e tatimeve ose zyra e gjobave — shkurt, pothuajse çdo letër zyrtare." },
    { f: "Çfarë ndodh me të dhënat e mia?", a: "Letrat tuaja mbeten të koduara në pajisjen tuaj. Për analizën, fotoja dërgohet një herë në mënyrë të sigurt te inteligjenca artificiale dhe fshihet atje më së voni pas 30 ditësh. Nuk ju duhet llogari." },
  ],
  locale: 'sq_AL', navLabel: 'Zgjidhni gjuhën',
  titel: 'BehördenKlar – kuptoni letrën e një institucioni gjerman',
  beschreibung: 'BehördenKlar i shpjegon letrat zyrtare gjermane me fjalë të thjeshta — në shqip. Bëni një foto, kuptoni, përgjigjuni saktë.',
  ogTitel: 'Ju erdhi një letër nga një institucion?',
  ogBeschreibung: 'Bëni një foto — BehördenKlar e shpjegon letrën me gjuhë të thjeshtë, në shqip. Lista e pritjes: 5 analiza falas.',
  h1a: 'Letër nga një institucion gjerman?', h1b: 'Më në fund e kuptueshme.',
  intro: 'Fotografoni letrën. BehördenKlar e shpjegon me fjalë të thjeshta — <strong>dhe në shqip</strong>. Me të gjitha afatet dhe një listë detyrash.',
  ctaHero: 'Në listën e pritjes', stempel: 'Së shpejti në iPhone',
  s1Titel: 'Para dhe pas', vorherLabel: 'Para · Letra origjinale (gjermanisht)', pfeil: 'një foto më vonë',
  nachherLabel: 'Pas · BehördenKlar në shqip',
  nachherText: 'Nëse nuk shkoni në takim pa një arsye të mirë, për një muaj merrni 10 % më pak para. Shkoni — ose anuloni në kohë.',
  hinweis: 'Aplikacioni i shpjegon letrat në gjermanisht të thjeshtë dhe i përkthen në më shumë se 25 gjuhë.',
  s2Titel: 'Si funksionon',
  schritt1T: 'Bëni foto', schritt1B: 'Fotografoni letrën — ose ngarkoni një PDF.',
  schritt2T: 'Kuptoni', schritt2B: 'Fjalë të thjeshta, në gjuhën tuaj. Një semafor tregon sa urgjente është.',
  schritt3T: 'Përgjigjuni saktë', schritt3B: 'Listë detyrash, kujtesë për afatin dhe një draft përgjigjeje gati.',
  s3Titel: 'Qasje e hershme', formularKopf: 'Formulari F-01 · Lista e pritjes', formH3: 'Jini ndër të parët',
  formText: 'Aplikacioni vjen së shpejti për iPhone. Regjistrohuni — do t’ju dërgojmë <strong>një</strong> email kur të nisë. Pa reklama.',
  bonus: '<strong>Dhurata juaj:</strong> analizoni <strong>5 letra falas</strong> në vend të 3. Kodin e merrni me email.',
  emailPlatzhalter: 'Adresa juaj e emailit', ctaForm: 'Regjistrohuni në listë',
  klein: 'Adresën e ruajmë vetëm për këtë mesazh të vetëm. Mund të çregjistroheni në çdo kohë.',
  datenschutz: 'Politika e privatësisë (gjermanisht)', impressum: 'Impressum (gjermanisht)', fussFrage: 'Keni pyetje?',
};

TEXTE.it = {
  s4Titel: "Domande frequenti",
  faq: [
    { f: "Quanto costa?", a: "Le prime 3 lettere sono gratis (5 con il codice della lista d’attesa). Poi acquisti credito: 5 analisi a 2,99 € o 15 a 6,99 €. Nessun abbonamento, nessun account." },
    { f: "Quali lettere può spiegare?", a: "Lettere del Jobcenter, dell’Ufficio stranieri, dell’assicurazione pensionistica, della cassa malattia, della cassa familiare (Kindergeld), dell’ufficio delle imposte o dell’ufficio sanzioni — in breve, quasi ogni lettera ufficiale." },
    { f: "Che fine fanno i miei dati?", a: "Le tue lettere restano cifrate sul tuo dispositivo. Per l’analisi la foto viene inviata una sola volta in modo sicuro all’IA e viene cancellata lì al più tardi dopo 30 giorni. Non serve un account." },
  ],
  locale: 'it_IT', navLabel: 'Scegli la lingua',
  titel: 'BehördenKlar – capire le lettere degli uffici tedeschi',
  beschreibung: 'BehördenKlar spiega le lettere ufficiali tedesche con parole semplici — in italiano. Scatta una foto, capisci, rispondi correttamente.',
  ogTitel: 'Hai ricevuto una lettera da un ufficio tedesco?',
  ogBeschreibung: 'Scatta una foto — BehördenKlar spiega la lettera in parole semplici, in italiano. Lista d’attesa: 5 analisi gratuite.',
  h1a: 'Una lettera da un ufficio tedesco?', h1b: 'Finalmente chiara.',
  intro: 'Fotografa la lettera. BehördenKlar la spiega con parole semplici — <strong>e in italiano</strong>. Con tutte le scadenze e un elenco di cose da fare.',
  ctaHero: 'Iscriviti alla lista', stempel: 'Presto su iPhone',
  s1Titel: 'Prima e dopo', vorherLabel: 'Prima · Lettera originale (tedesco)', pfeil: 'una foto dopo',
  nachherLabel: 'Dopo · BehördenKlar in italiano',
  nachherText: 'Se non vai all’appuntamento senza un valido motivo, per un mese ricevi il 10 % di denaro in meno. Vai — oppure disdici per tempo.',
  hinweis: 'L’app spiega le lettere in tedesco semplice e le traduce in più di 25 lingue.',
  s2Titel: 'Come funziona',
  schritt1T: 'Scatta una foto', schritt1B: 'Fotografa la lettera — oppure carica un PDF.',
  schritt2T: 'Capisci', schritt2B: 'Parole semplici, nella tua lingua. Un semaforo mostra quanto è urgente.',
  schritt3T: 'Rispondi correttamente', schritt3B: 'Elenco di cose da fare, promemoria per la scadenza e una bozza di risposta già pronta.',
  s3Titel: 'Accesso anticipato', formularKopf: 'Modulo F-01 · Lista d’attesa', formH3: 'Sii tra i primi',
  formText: 'L’app arriva presto per iPhone. Iscriviti — ti invieremo <strong>una sola</strong> email al lancio. Niente pubblicità.',
  bonus: '<strong>Il tuo regalo:</strong> analizza <strong>5 lettere gratis</strong> invece di 3. Ricevi il codice via email.',
  emailPlatzhalter: 'Il tuo indirizzo email', ctaForm: 'Iscriviti alla lista',
  klein: 'Conserviamo il tuo indirizzo solo per questo unico messaggio. Puoi cancellarti in qualsiasi momento.',
  datenschutz: 'Informativa sulla privacy (in tedesco)', impressum: 'Note legali (in tedesco)', fussFrage: 'Hai domande?',
};

TEXTE.el = {
  s4Titel: "Συχνές ερωτήσεις",
  faq: [
    { f: "Πόσο κοστίζει;", a: "Τα πρώτα 3 γράμματα είναι δωρεάν (5 με τον κωδικό της λίστας αναμονής). Έπειτα αγοράζετε μονάδες: 5 αναλύσεις 2,99 € ή 15 για 6,99 €. Χωρίς συνδρομή, χωρίς λογαριασμό." },
    { f: "Ποια γράμματα μπορεί να εξηγήσει;", a: "Γράμματα από το Jobcenter, την Υπηρεσία Αλλοδαπών, την ασφάλιση σύνταξης, το ταμείο υγείας, το οικογενειακό ταμείο (Kindergeld), την εφορία ή την υπηρεσία προστίμων — με λίγα λόγια, σχεδόν κάθε επίσημο γράμμα." },
    { f: "Τι γίνεται με τα δεδομένα μου;", a: "Τα γράμματά σας παραμένουν κρυπτογραφημένα στη συσκευή σας. Για την ανάλυση η φωτογραφία στέλνεται μία φορά με ασφάλεια στην ΤΝ και διαγράφεται εκεί το αργότερο μετά από 30 ημέρες. Δεν χρειάζεστε λογαριασμό." },
  ],
  locale: 'el_GR', navLabel: 'Επιλέξτε γλώσσα',
  titel: 'BehördenKlar – κατανοήστε το γράμμα γερμανικής υπηρεσίας',
  beschreibung: 'Το BehördenKlar εξηγεί τα γερμανικά επίσημα γράμματα με απλά λόγια — στα ελληνικά. Φωτογραφίστε, καταλάβετε, απαντήστε σωστά.',
  ogTitel: 'Λάβατε γράμμα από υπηρεσία;',
  ogBeschreibung: 'Φωτογραφίστε — το BehördenKlar εξηγεί το γράμμα σε απλή γλώσσα, στα ελληνικά. Λίστα αναμονής: 5 δωρεάν αναλύσεις.',
  h1a: 'Γράμμα από γερμανική υπηρεσία;', h1b: 'Επιτέλους κατανοητό.',
  intro: 'Φωτογραφίστε το γράμμα. Το BehördenKlar το εξηγεί με απλά λόγια — <strong>και στα ελληνικά</strong>. Με όλες τις προθεσμίες και λίστα ενεργειών.',
  ctaHero: 'Στη λίστα αναμονής', stempel: 'Σύντομα στο iPhone',
  s1Titel: 'Πριν και μετά', vorherLabel: 'Πριν · Πρωτότυπο (στα γερμανικά)', pfeil: 'μία φωτογραφία αργότερα',
  nachherLabel: 'Μετά · BehördenKlar στα ελληνικά',
  nachherText: 'Αν δεν πάτε στο ραντεβού χωρίς σοβαρό λόγο, για έναν μήνα θα παίρνετε 10 % λιγότερα χρήματα. Πηγαίνετε — ή ακυρώστε έγκαιρα.',
  hinweis: 'Η εφαρμογή εξηγεί τα γράμματα σε απλά γερμανικά και τα μεταφράζει σε πάνω από 25 γλώσσες.',
  s2Titel: 'Πώς λειτουργεί',
  schritt1T: 'Φωτογραφίστε', schritt1B: 'Φωτογραφίστε το γράμμα — ή ανεβάστε PDF.',
  schritt2T: 'Καταλάβετε', schritt2B: 'Απλά λόγια στη γλώσσα σας. Ένα φανάρι δείχνει πόσο επείγον είναι.',
  schritt3T: 'Απαντήστε σωστά', schritt3B: 'Λίστα ενεργειών, υπενθύμιση προθεσμίας και έτοιμο προσχέδιο απάντησης.',
  s3Titel: 'Πρώιμη πρόσβαση', formularKopf: 'Έντυπο F-01 · Λίστα αναμονής', formH3: 'Γίνετε από τους πρώτους',
  formText: 'Η εφαρμογή έρχεται σύντομα για iPhone. Εγγραφείτε — θα σας στείλουμε <strong>ένα</strong> email στην κυκλοφορία. Χωρίς διαφημίσεις.',
  bonus: '<strong>Το δώρο σας:</strong> <strong>5 γράμματα δωρεάν</strong> αντί για 3. Ο κωδικός έρχεται με email.',
  emailPlatzhalter: 'Η διεύθυνση email σας', ctaForm: 'Εγγραφή στη λίστα',
  klein: 'Αποθηκεύουμε τη διεύθυνση μόνο για αυτό το ένα μήνυμα. Μπορείτε να διαγραφείτε ανά πάσα στιγμή.',
  datenschutz: 'Πολιτική απορρήτου (στα γερμανικά)', impressum: 'Στοιχεία έκδοσης (στα γερμανικά)', fussFrage: 'Έχετε ερωτήσεις;',
};

TEXTE.es = {
  s4Titel: "Preguntas frecuentes",
  faq: [
    { f: "¿Cuánto cuesta?", a: "Las primeras 3 cartas son gratis (5 con el código de la lista de espera). Después compras saldo: 5 análisis por 2,99 € o 15 por 6,99 €. Sin suscripción y sin cuenta." },
    { f: "¿Qué cartas puede explicar?", a: "Cartas del Jobcenter, de la Oficina de Extranjería, del seguro de pensiones, de la mutua de salud, de la caja familiar (Kindergeld), de Hacienda o de la oficina de multas — en resumen, casi cualquier carta oficial." },
    { f: "¿Qué pasa con mis datos?", a: "Tus cartas permanecen cifradas en tu propio dispositivo. Para el análisis, la foto se envía una sola vez de forma segura a la IA y allí se borra como máximo a los 30 días. No necesitas cuenta." },
  ],
  locale: 'es_ES', navLabel: 'Elige idioma',
  titel: 'BehördenKlar – entiende las cartas de las oficinas alemanas',
  beschreibung: 'BehördenKlar explica las cartas oficiales alemanas con palabras sencillas — en español. Haz una foto, entiéndela, responde bien.',
  ogTitel: '¿Has recibido una carta de una oficina alemana?',
  ogBeschreibung: 'Haz una foto — BehördenKlar explica la carta en lenguaje sencillo, en español. Lista de espera: 5 análisis gratis.',
  h1a: '¿Una carta de una oficina alemana?', h1b: 'Por fin se entiende.',
  intro: 'Haz una foto de la carta. BehördenKlar la explica con palabras sencillas — <strong>y en español</strong>. Con todos los plazos y una lista de tareas.',
  ctaHero: 'Apuntarme a la lista', stempel: 'Pronto en iPhone',
  s1Titel: 'Antes y después', vorherLabel: 'Antes · Carta original (en alemán)', pfeil: 'una foto después',
  nachherLabel: 'Después · BehördenKlar en español',
  nachherText: 'Si no acudes a la cita sin un buen motivo, durante un mes recibirás un 10 % menos de dinero. Acude — o cancela a tiempo.',
  hinweis: 'La aplicación explica las cartas en alemán sencillo y las traduce a más de 25 idiomas.',
  s2Titel: 'Cómo funciona',
  schritt1T: 'Haz una foto', schritt1B: 'Fotografía la carta — o sube un PDF.',
  schritt2T: 'Entiende', schritt2B: 'Palabras sencillas, en tu idioma. Un semáforo muestra la urgencia.',
  schritt3T: 'Responde bien', schritt3B: 'Lista de tareas, recordatorio del plazo y un borrador de respuesta listo.',
  s3Titel: 'Acceso anticipado', formularKopf: 'Formulario F-01 · Lista de espera', formH3: 'Sé de los primeros',
  formText: 'La aplicación llega pronto para iPhone. Apúntate — te enviaremos <strong>un solo</strong> correo cuando esté lista. Sin publicidad.',
  bonus: '<strong>Tu regalo:</strong> analiza <strong>5 cartas gratis</strong> en vez de 3. Recibes el código por correo.',
  emailPlatzhalter: 'Tu dirección de correo', ctaForm: 'Apuntarme a la lista',
  klein: 'Guardamos tu dirección solo para este único mensaje. Puedes darte de baja cuando quieras.',
  datenschutz: 'Política de privacidad (en alemán)', impressum: 'Aviso legal (en alemán)', fussFrage: '¿Tienes preguntas?',
};

TEXTE.pt = {
  s4Titel: "Perguntas frequentes",
  faq: [
    { f: "Quanto custa?", a: "As primeiras 3 cartas são grátis (5 com o código da lista de espera). Depois compra saldo: 5 análises por 2,99 € ou 15 por 6,99 €. Sem assinatura e sem conta." },
    { f: "Que cartas consegue explicar?", a: "Cartas do Jobcenter, do Serviço de Estrangeiros, do seguro de pensões, da caixa de saúde, da caixa familiar (Kindergeld), das finanças ou do serviço de multas — em resumo, quase qualquer carta oficial." },
    { f: "O que acontece aos meus dados?", a: "As suas cartas ficam cifradas no seu próprio dispositivo. Para a análise, a foto é enviada uma única vez de forma segura para a IA e é apagada lá no máximo ao fim de 30 dias. Não precisa de conta." },
  ],
  locale: 'pt_PT', navLabel: 'Escolha o idioma',
  titel: 'BehördenKlar – perceber as cartas das repartições alemãs',
  beschreibung: 'O BehördenKlar explica as cartas oficiais alemãs com palavras simples — em português. Tire uma foto, perceba, responda corretamente.',
  ogTitel: 'Recebeu uma carta de uma repartição alemã?',
  ogBeschreibung: 'Tire uma foto — o BehördenKlar explica a carta em linguagem simples, em português. Lista de espera: 5 análises grátis.',
  h1a: 'Uma carta de uma repartição alemã?', h1b: 'Finalmente clara.',
  intro: 'Fotografe a carta. O BehördenKlar explica-a com palavras simples — <strong>e em português</strong>. Com todos os prazos e uma lista de tarefas.',
  ctaHero: 'Entrar na lista de espera', stempel: 'Brevemente no iPhone',
  s1Titel: 'Antes e depois', vorherLabel: 'Antes · Carta original (em alemão)', pfeil: 'uma foto depois',
  nachherLabel: 'Depois · BehördenKlar em português',
  nachherText: 'Se não for à marcação sem um bom motivo, durante um mês recebe menos 10 % de dinheiro. Vá — ou cancele a tempo.',
  hinweis: 'A aplicação explica as cartas em alemão simples e traduz para mais de 25 idiomas.',
  s2Titel: 'Como funciona',
  schritt1T: 'Tire uma foto', schritt1B: 'Fotografe a carta — ou carregue um PDF.',
  schritt2T: 'Perceba', schritt2B: 'Palavras simples, na sua língua. Um semáforo mostra a urgência.',
  schritt3T: 'Responda corretamente', schritt3B: 'Lista de tarefas, lembrete do prazo e um rascunho de resposta pronto.',
  s3Titel: 'Acesso antecipado', formularKopf: 'Formulário F-01 · Lista de espera', formH3: 'Esteja entre os primeiros',
  formText: 'A aplicação chega em breve para iPhone. Inscreva-se — enviamos <strong>um</strong> e-mail quando estiver pronta. Sem publicidade.',
  bonus: '<strong>O seu presente:</strong> analise <strong>5 cartas grátis</strong> em vez de 3. Recebe o código por e-mail.',
  emailPlatzhalter: 'O seu endereço de e-mail', ctaForm: 'Entrar na lista',
  klein: 'Guardamos o endereço apenas para esta única mensagem. Pode cancelar a qualquer momento.',
  datenschutz: 'Política de privacidade (em alemão)', impressum: 'Ficha técnica (em alemão)', fussFrage: 'Tem dúvidas?',
};

TEXTE.fr = {
  s4Titel: "Questions fréquentes",
  faq: [
    { f: "Combien ça coûte ?", a: "Les 3 premiers courriers sont gratuits (5 avec le code de la liste d’attente). Ensuite vous achetez du crédit : 5 analyses pour 2,99 € ou 15 pour 6,99 €. Sans abonnement et sans compte." },
    { f: "Quels courriers peut-elle expliquer ?", a: "Les courriers du Jobcenter, du service des étrangers, de l’assurance retraite, de la caisse maladie, de la caisse familiale (Kindergeld), du fisc ou du service des amendes — bref, presque tout courrier officiel." },
    { f: "Que deviennent mes données ?", a: "Vos courriers restent chiffrés sur votre appareil. Pour l’analyse, la photo est envoyée une seule fois de façon sécurisée à l’IA et y est supprimée au plus tard au bout de 30 jours. Aucun compte nécessaire." },
  ],
  locale: 'fr_FR', navLabel: 'Choisir la langue',
  titel: 'BehördenKlar – comprendre les courriers administratifs allemands',
  beschreibung: 'BehördenKlar explique les courriers administratifs allemands avec des mots simples — en français. Prenez une photo, comprenez, répondez correctement.',
  ogTitel: 'Vous avez reçu un courrier administratif allemand ?',
  ogBeschreibung: 'Prenez une photo — BehördenKlar explique le courrier en langage simple, en français. Liste d’attente : 5 analyses gratuites.',
  h1a: 'Un courrier de l’administration allemande ?', h1b: 'Enfin compréhensible.',
  intro: 'Photographiez le courrier. BehördenKlar l’explique avec des mots simples — <strong>et en français</strong>. Avec tous les délais et une liste de choses à faire.',
  ctaHero: 'Rejoindre la liste d’attente', stempel: 'Bientôt sur iPhone',
  s1Titel: 'Avant et après', vorherLabel: 'Avant · Courrier original (en allemand)', pfeil: 'une photo plus tard',
  nachherLabel: 'Après · BehördenKlar en français',
  nachherText: 'Si vous manquez le rendez-vous sans motif valable, vous recevrez 10 % d’argent en moins pendant un mois. Allez-y — ou annulez à temps.',
  hinweis: 'L’application explique les courriers en allemand simple et les traduit dans plus de 25 langues.',
  s2Titel: 'Comment ça marche',
  schritt1T: 'Prenez une photo', schritt1B: 'Photographiez le courrier — ou téléversez un PDF.',
  schritt2T: 'Comprenez', schritt2B: 'Des mots simples, dans votre langue. Un feu tricolore indique l’urgence.',
  schritt3T: 'Répondez correctement', schritt3B: 'Liste de tâches, rappel du délai et un brouillon de réponse tout prêt.',
  s3Titel: 'Accès anticipé', formularKopf: 'Formulaire F-01 · Liste d’attente', formH3: 'Soyez parmi les premiers',
  formText: 'L’application arrive bientôt sur iPhone. Inscrivez-vous — nous vous enverrons <strong>un seul</strong> e-mail au lancement. Sans publicité.',
  bonus: '<strong>Votre cadeau :</strong> analysez <strong>5 courriers gratuits</strong> au lieu de 3. Vous recevez le code par e-mail.',
  emailPlatzhalter: 'Votre adresse e-mail', ctaForm: 'Rejoindre la liste',
  klein: 'Nous conservons votre adresse uniquement pour ce seul message. Vous pouvez vous désinscrire à tout moment.',
  datenschutz: 'Politique de confidentialité (en allemand)', impressum: 'Mentions légales (en allemand)', fussFrage: 'Des questions ?',
};

TEXTE.hu = {
  s4Titel: "Gyakori kérdések",
  faq: [
    { f: "Mennyibe kerül?", a: "Az első 3 levél ingyenes (a várólista kódjával 5). Utána egyenleget vásárol: 5 elemzés 2,99 €, 15 elemzés 6,99 €. Előfizetés és fiók nélkül." },
    { f: "Milyen leveleket tud elmagyarázni?", a: "A Jobcenter, az idegenrendészet, a nyugdíjbiztosító, a betegpénztár, a családi pénztár (Kindergeld), az adóhivatal vagy a bírságoló hatóság leveleit — röviden szinte minden hivatalos levelet." },
    { f: "Mi történik az adataimmal?", a: "A levelei titkosítva a saját készülékén maradnak. Az elemzéshez a fénykép egyszer, biztonságosan kerül el az MI-hez, és ott legkésőbb 30 nap múlva törlődik. Nincs szükség fiókra." },
  ],
  locale: 'hu_HU', navLabel: 'Válasszon nyelvet',
  titel: 'BehördenKlar – értse meg a német hivatali levelet',
  beschreibung: 'A BehördenKlar egyszerű szavakkal magyarázza el a német hivatali leveleket — magyarul. Fényképezze le, értse meg, válaszoljon helyesen.',
  ogTitel: 'Levelet kapott egy német hivataltól?',
  ogBeschreibung: 'Fényképezze le — a BehördenKlar egyszerű nyelven, magyarul magyarázza el a levelet. Várólista: 5 ingyenes elemzés.',
  h1a: 'Levél egy német hivataltól?', h1b: 'Végre érthető.',
  intro: 'Fényképezze le a levelet. A BehördenKlar egyszerű szavakkal magyarázza el — <strong>és magyarul</strong>. Minden határidővel és teendőlistával.',
  ctaHero: 'Feliratkozom a várólistára', stempel: 'Hamarosan iPhone-on',
  s1Titel: 'Előtte és utána', vorherLabel: 'Előtte · Eredeti levél (németül)', pfeil: 'egy fényképpel később',
  nachherLabel: 'Utána · BehördenKlar magyarul',
  nachherText: 'Ha alapos ok nélkül nem megy el az időpontra, egy hónapig 10 %-kal kevesebb pénzt kap. Menjen el — vagy időben mondja le.',
  hinweis: 'Az alkalmazás egyszerű németül magyarázza a leveleket, és több mint 25 nyelvre fordítja.',
  s2Titel: 'Hogyan működik',
  schritt1T: 'Fényképezzen', schritt1B: 'Fényképezze le a levelet — vagy töltsön fel PDF-et.',
  schritt2T: 'Értse meg', schritt2B: 'Egyszerű szavak az Ön nyelvén. Egy jelzőlámpa mutatja, mennyire sürgős.',
  schritt3T: 'Válaszoljon helyesen', schritt3B: 'Teendőlista, határidő-emlékeztető és kész válaszpiszkozat.',
  s3Titel: 'Korai hozzáférés', formularKopf: 'F-01 űrlap · Várólista', formH3: 'Legyen az elsők között',
  formText: 'Az alkalmazás hamarosan megjelenik iPhone-ra. Iratkozzon fel — induláskor <strong>egyetlen</strong> e-mailt küldünk. Reklám nélkül.',
  bonus: '<strong>Az Ön ajándéka:</strong> <strong>5 levél ingyen</strong> 3 helyett. A kódot e-mailben kapja.',
  emailPlatzhalter: 'Az Ön e-mail címe', ctaForm: 'Feliratkozom a listára',
  klein: 'A címet csak ehhez az egy üzenethez tároljuk. Bármikor leiratkozhat.',
  datenschutz: 'Adatvédelmi tájékoztató (németül)', impressum: 'Impresszum (németül)', fussFrage: 'Kérdése van?',
};

TEXTE.vi = {
  s4Titel: "Câu hỏi thường gặp",
  faq: [
    { f: "Giá bao nhiêu?", a: "3 lá thư đầu tiên miễn phí (5 nếu có mã từ danh sách chờ). Sau đó bạn mua lượt: 5 lần phân tích 2,99 €, 15 lần 6,99 €. Không thuê bao, không cần tài khoản." },
    { f: "Ứng dụng giải thích được những thư nào?", a: "Thư từ Jobcenter, Sở Ngoại kiều, bảo hiểm hưu trí, bảo hiểm y tế, quỹ gia đình (Kindergeld), sở thuế hoặc cơ quan xử phạt — nói ngắn gọn là hầu hết mọi thư chính thức." },
    { f: "Dữ liệu của tôi thì sao?", a: "Thư của bạn được mã hóa và nằm trên thiết bị của bạn. Để phân tích, ảnh được gửi một lần duy nhất và an toàn tới AI, rồi bị xóa ở đó chậm nhất sau 30 ngày. Bạn không cần tài khoản." },
  ],
  locale: 'vi_VN', navLabel: 'Chọn ngôn ngữ',
  titel: 'BehördenKlar – hiểu thư từ cơ quan công quyền Đức',
  beschreibung: 'BehördenKlar giải thích thư công quyền Đức bằng lời đơn giản — bằng tiếng Việt. Chụp ảnh, hiểu, trả lời đúng.',
  ogTitel: 'Bạn nhận được thư từ cơ quan Đức?',
  ogBeschreibung: 'Chụp ảnh — BehördenKlar giải thích lá thư bằng ngôn ngữ đơn giản, bằng tiếng Việt. Danh sách chờ: 5 lần phân tích miễn phí.',
  h1a: 'Thư từ một cơ quan Đức?', h1b: 'Cuối cùng cũng hiểu được.',
  intro: 'Chụp ảnh lá thư. BehördenKlar giải thích bằng lời đơn giản — <strong>và bằng tiếng Việt</strong>. Kèm mọi thời hạn và danh sách việc cần làm.',
  ctaHero: 'Vào danh sách chờ', stempel: 'Sắp có trên iPhone',
  s1Titel: 'Trước và sau', vorherLabel: 'Trước · Thư gốc (tiếng Đức)', pfeil: 'một tấm ảnh sau',
  nachherLabel: 'Sau · BehördenKlar bằng tiếng Việt',
  nachherText: 'Nếu bạn không đến hẹn mà không có lý do chính đáng, trong một tháng bạn sẽ nhận ít hơn 10 % tiền. Hãy đến — hoặc hủy hẹn kịp thời.',
  hinweis: 'Ứng dụng giải thích thư bằng tiếng Đức đơn giản và dịch sang hơn 25 ngôn ngữ.',
  s2Titel: 'Cách hoạt động',
  schritt1T: 'Chụp ảnh', schritt1B: 'Chụp ảnh lá thư — hoặc tải lên tệp PDF.',
  schritt2T: 'Hiểu', schritt2B: 'Lời lẽ đơn giản, bằng ngôn ngữ của bạn. Đèn tín hiệu cho biết mức độ khẩn cấp.',
  schritt3T: 'Trả lời đúng', schritt3B: 'Danh sách việc cần làm, nhắc nhở thời hạn và bản nháp trả lời có sẵn.',
  s3Titel: 'Truy cập sớm', formularKopf: 'Mẫu F-01 · Danh sách chờ', formH3: 'Hãy là người đầu tiên',
  formText: 'Ứng dụng sắp có cho iPhone. Hãy đăng ký — chúng tôi sẽ gửi <strong>một</strong> email khi ra mắt. Không quảng cáo.',
  bonus: '<strong>Quà của bạn:</strong> phân tích <strong>5 lá thư miễn phí</strong> thay vì 3. Bạn nhận mã qua email.',
  emailPlatzhalter: 'Địa chỉ email của bạn', ctaForm: 'Đăng ký vào danh sách',
  klein: 'Chúng tôi chỉ lưu địa chỉ cho một tin nhắn duy nhất này. Bạn có thể hủy đăng ký bất cứ lúc nào.',
  datenschutz: 'Chính sách bảo mật (tiếng Đức)', impressum: 'Thông tin pháp lý (tiếng Đức)', fussFrage: 'Bạn có câu hỏi?',
};

TEXTE.hi = {
  s4Titel: "अक्सर पूछे जाने वाले सवाल",
  faq: [
    { f: "इसकी कीमत क्या है?", a: "पहली 3 चिट्ठियाँ मुफ़्त हैं (प्रतीक्षा सूची के कोड से 5)। उसके बाद आप क्रेडिट खरीदते हैं: 5 विश्लेषण 2,99 € में या 15 विश्लेषण 6,99 € में। कोई सदस्यता नहीं, कोई खाता नहीं।" },
    { f: "यह कौन-सी चिट्ठियाँ समझा सकता है?", a: "जॉबसेंटर, विदेशी विभाग, पेंशन बीमा, स्वास्थ्य बीमा, परिवार कोष (Kindergeld), कर विभाग या जुर्माना विभाग की चिट्ठियाँ — संक्षेप में, लगभग हर सरकारी चिट्ठी।" },
    { f: "मेरे डेटा का क्या होता है?", a: "आपकी चिट्ठियाँ आपके अपने उपकरण पर एन्क्रिप्टेड रहती हैं। विश्लेषण के लिए फ़ोटो एक बार सुरक्षित रूप से एआई को भेजी जाती है और वहाँ अधिकतम 30 दिनों में मिटा दी जाती है। आपको खाते की ज़रूरत नहीं।" },
  ],
  locale: 'hi_IN', navLabel: 'भाषा चुनें',
  titel: 'BehördenKlar – जर्मन सरकारी चिट्ठी समझें',
  beschreibung: 'BehördenKlar जर्मन सरकारी चिट्ठियों को आसान शब्दों में समझाता है — हिन्दी में। फ़ोटो लें, समझें, सही जवाब दें।',
  ogTitel: 'जर्मन दफ़्तर से चिट्ठी आई है?',
  ogBeschreibung: 'फ़ोटो लें — BehördenKlar चिट्ठी को आसान भाषा में, हिन्दी में समझाता है। प्रतीक्षा सूची: 5 मुफ़्त विश्लेषण।',
  h1a: 'जर्मन दफ़्तर से चिट्ठी?', h1b: 'अब समझ में आती है।',
  intro: 'चिट्ठी की फ़ोटो लें। BehördenKlar उसे आसान शब्दों में — <strong>और हिन्दी में</strong> — समझाता है। सभी समय-सीमाओं और काम की सूची के साथ।',
  ctaHero: 'प्रतीक्षा सूची में जुड़ें', stempel: 'जल्द ही iPhone पर',
  s1Titel: 'पहले और बाद में', vorherLabel: 'पहले · मूल चिट्ठी (जर्मन में)', pfeil: 'एक फ़ोटो के बाद',
  nachherLabel: 'बाद में · BehördenKlar हिन्दी में',
  nachherText: 'यदि आप बिना उचित कारण के मुलाक़ात पर नहीं आते, तो एक महीने तक आपको 10 % कम पैसा मिलेगा। जाइए — या समय रहते रद्द कीजिए।',
  hinweis: 'ऐप चिट्ठियों को आसान जर्मन में समझाता है और 25 से अधिक भाषाओं में अनुवाद करता है।',
  s2Titel: 'यह कैसे काम करता है',
  schritt1T: 'फ़ोटो लें', schritt1B: 'चिट्ठी की फ़ोटो लें — या PDF अपलोड करें।',
  schritt2T: 'समझें', schritt2B: 'आपकी भाषा में आसान शब्द। एक ट्रैफ़िक लाइट दिखाती है कि कितना ज़रूरी है।',
  schritt3T: 'सही जवाब दें', schritt3B: 'काम की सूची, समय-सीमा की याद और तैयार जवाब का मसौदा।',
  s3Titel: 'पहले पहुँच', formularKopf: 'फ़ॉर्म F-01 · प्रतीक्षा सूची', formH3: 'सबसे पहले जुड़ें',
  formText: 'ऐप जल्द ही iPhone के लिए आ रहा है। नाम लिखवाइए — शुरू होते ही हम <strong>एक</strong> ई-मेल भेजेंगे। कोई विज्ञापन नहीं।',
  bonus: '<strong>आपका उपहार:</strong> 3 के बजाय <strong>5 चिट्ठियाँ मुफ़्त</strong>। कोड ई-मेल से मिलेगा।',
  emailPlatzhalter: 'आपका ई-मेल पता', ctaForm: 'सूची में नाम लिखवाएँ',
  klein: 'हम आपका पता केवल इसी एक संदेश के लिए रखते हैं। आप कभी भी हटा सकते हैं।',
  datenschutz: 'गोपनीयता नीति (जर्मन में)', impressum: 'प्रकाशक जानकारी (जर्मन में)', fussFrage: 'कोई सवाल?',
};

TEXTE.ur = {
  s4Titel: "اکثر پوچھے جانے والے سوالات",
  faq: [
    { f: "اس کی قیمت کیا ہے؟", a: "پہلے 3 خط مفت ہیں (انتظار کی فہرست کے کوڈ کے ساتھ 5)۔ اس کے بعد آپ کریڈٹ خریدتے ہیں: 5 تجزیے 2,99 € میں یا 15 تجزیے 6,99 € میں۔ کوئی سبسکرپشن نہیں، کوئی اکاؤنٹ نہیں۔" },
    { f: "یہ کون سے خط سمجھا سکتا ہے؟", a: "جاب سینٹر، غیر ملکی دفتر، پنشن انشورنس، ہیلتھ انشورنس، فیملی فنڈ (Kindergeld)، ٹیکس دفتر یا جرمانہ دفتر کے خطوط — مختصراً تقریباً ہر سرکاری خط۔" },
    { f: "میرے ڈیٹا کا کیا ہوتا ہے؟", a: "آپ کے خطوط آپ کے اپنے آلے پر خفیہ شکل میں رہتے ہیں۔ تجزیے کے لیے تصویر ایک بار محفوظ طریقے سے اے آئی کو بھیجی جاتی ہے اور وہاں زیادہ سے زیادہ 30 دن میں مٹا دی جاتی ہے۔ آپ کو اکاؤنٹ کی ضرورت نہیں۔" },
  ],
  locale: 'ur_PK', navLabel: 'زبان منتخب کریں',
  titel: 'BehördenKlar – جرمن سرکاری خط سمجھیں',
  beschreibung: 'BehördenKlar جرمن سرکاری خطوط کو آسان الفاظ میں سمجھاتا ہے — اردو میں۔ تصویر لیں، سمجھیں، درست جواب دیں۔',
  ogTitel: 'جرمن دفتر سے خط آیا ہے؟',
  ogBeschreibung: 'تصویر لیں — BehördenKlar خط کو آسان زبان میں، اردو میں سمجھاتا ہے۔ انتظار کی فہرست: 5 مفت تجزیے۔',
  h1a: 'جرمن دفتر سے خط؟', h1b: 'اب سمجھ میں آتا ہے۔',
  intro: 'خط کی تصویر لیں۔ BehördenKlar اسے آسان الفاظ میں — <strong>اور اردو میں</strong> — سمجھاتا ہے۔ تمام آخری تاریخوں اور کاموں کی فہرست کے ساتھ۔',
  ctaHero: 'انتظار کی فہرست میں شامل ہوں', stempel: 'جلد ہی iPhone پر',
  s1Titel: 'پہلے اور بعد میں', vorherLabel: 'پہلے · اصل خط (جرمن میں)', pfeil: 'ایک تصویر کے بعد',
  nachherLabel: 'بعد میں · BehördenKlar اردو میں',
  nachherText: 'اگر آپ بغیر مناسب وجہ کے ملاقات پر نہ آئیں، تو ایک مہینے تک آپ کو 10 فیصد کم رقم ملے گی۔ جائیں — یا وقت پر منسوخ کریں۔',
  hinweis: 'ایپ خطوط کو آسان جرمن میں سمجھاتی ہے اور 25 سے زیادہ زبانوں میں ترجمہ کرتی ہے۔',
  s2Titel: 'یہ کیسے کام کرتا ہے',
  schritt1T: 'تصویر لیں', schritt1B: 'خط کی تصویر لیں — یا PDF اپ لوڈ کریں۔',
  schritt2T: 'سمجھیں', schritt2B: 'آپ کی زبان میں آسان الفاظ۔ ایک اشارہ بتاتا ہے کہ کتنا ضروری ہے۔',
  schritt3T: 'درست جواب دیں', schritt3B: 'کاموں کی فہرست، آخری تاریخ کی یاد دہانی اور تیار جواب کا مسودہ۔',
  s3Titel: 'جلد رسائی', formularKopf: 'فارم F-01 · انتظار کی فہرست', formH3: 'سب سے پہلے شامل ہوں',
  formText: 'ایپ جلد ہی iPhone کے لیے آ رہی ہے۔ نام درج کرائیں — شروع ہوتے ہی ہم <strong>ایک</strong> ای میل بھیجیں گے۔ کوئی اشتہار نہیں۔',
  bonus: '<strong>آپ کا تحفہ:</strong> 3 کے بجائے <strong>5 خطوط مفت</strong>۔ کوڈ ای میل سے ملے گا۔',
  emailPlatzhalter: 'آپ کا ای میل پتہ', ctaForm: 'فہرست میں شامل ہوں',
  klein: 'ہم آپ کا پتہ صرف اسی ایک پیغام کے لیے محفوظ رکھتے ہیں۔ آپ کبھی بھی خارج ہو سکتے ہیں۔',
  datenschutz: 'رازداری کی پالیسی (جرمن میں)', impressum: 'اشاعتی معلومات (جرمن میں)', fussFrage: 'کوئی سوال؟',
};

TEXTE.ps = {
  s4Titel: "ډېرې پوښتل شوې پوښتنې",
  faq: [
    { f: "بیه یې څومره ده؟", a: "لومړي ۳ لیکونه وړیا دي (د انتظار لړلیک کوډ سره ۵). وروسته تاسو کریډیټ اخلئ: ۵ شننې په ۲٫۹۹ یورو یا ۱۵ په ۶٫۹۹ یورو. نه ګډون، نه حساب." },
    { f: "کوم لیکونه رابرسېره کولی شي؟", a: "د جاب سنټر، د بهرنیانو ادارې، د تقاعد بیمې، روغتیايي بیمې، کورنۍ صندوق (Kindergeld)، مالیې ادارې یا د جریمو ادارې لیکونه — په لنډه توګه نږدې هر رسمي لیک." },
    { f: "زما معلوماتو ته څه کیږي؟", a: "ستاسو لیکونه پټ شوي ستاسو په خپله وسیله پاتې کیږي. د شننې لپاره عکس یو ځل په خوندي ډول مصنوعي ځیرکتیا ته لیږل کیږي او هلته تر ۳۰ ورځو وروسته ړنګېږي. حساب ته اړتیا نشته." },
  ],
  locale: 'ps_AF', navLabel: 'ژبه وټاکئ',
  titel: 'BehördenKlar – د آلمان رسمي لیکونه پوه شئ',
  beschreibung: 'BehördenKlar د آلمان رسمي لیکونه په ساده کلمو — په پښتو — تشریح کوي. عکس واخلئ، پوه شئ، سم ځواب ورکړئ.',
  ogTitel: 'د آلمان له ادارې څخه لیک راغلی؟',
  ogBeschreibung: 'عکس واخلئ — BehördenKlar لیک په ساده ژبه، په پښتو تشریح کوي. د انتظار لړلیک: ۵ وړیا شننې.',
  h1a: 'د آلمان له یوې ادارې څخه لیک؟', h1b: 'اوس پرې پوهېږئ.',
  intro: 'د لیک عکس واخلئ. BehördenKlar یې په ساده کلمو — <strong>او په پښتو</strong> — تشریح کوي. د ټولو وختونو او د کارونو لیست سره.',
  ctaHero: 'د انتظار لړلیک ته ننوځئ', stempel: 'ډېر ژر په iPhone کې',
  s1Titel: 'مخکې او وروسته', vorherLabel: 'مخکې · اصلي لیک (په آلماني)', pfeil: 'یو عکس وروسته',
  nachherLabel: 'وروسته · BehördenKlar په پښتو',
  nachherText: 'که تاسو پرته له مهم دلیله ټاکنې ته ورنشئ، یوه میاشت به ۱۰ سلنه لږې پیسې ترلاسه کړئ. ورشئ — یا یې پر وخت لغوه کړئ.',
  hinweis: 'اپلیکیشن لیکونه په ساده آلماني تشریح کوي او له ۲۵ څخه زیاتو ژبو ته یې ژباړي.',
  s2Titel: 'څنګه کار کوي',
  schritt1T: 'عکس واخلئ', schritt1B: 'د لیک عکس واخلئ — یا PDF پورته کړئ.',
  schritt2T: 'پوه شئ', schritt2B: 'ساده کلمې ستاسو په ژبه. یوه اشاره ښیي چې څومره بیړنی دی.',
  schritt3T: 'سم ځواب ورکړئ', schritt3B: 'د کارونو لیست، د وخت یادونه او چمتو شوی ځواب.',
  s3Titel: 'لومړنی لاسرسی', formularKopf: 'فورمه F-01 · د انتظار لړلیک', formH3: 'له لومړیو څخه اوسئ',
  formText: 'اپلیکیشن به ډېر ژر د iPhone لپاره راشي. نوم ولیکئ — کله چې پیل شي موږ به <strong>یو</strong> بریښنالیک درولېږو. هېڅ اعلان نشته.',
  bonus: '<strong>ستاسو ډالۍ:</strong> د ۳ پرځای <strong>۵ لیکونه وړیا</strong>. کوډ به په بریښنالیک ترلاسه کړئ.',
  emailPlatzhalter: 'ستاسو بریښنالیک پته', ctaForm: 'په لړلیک کې نوم ولیکئ',
  klein: 'موږ ستاسو پته یوازې د همدې یو پیغام لپاره ساتو. هر وخت کولی شئ ځان ایسته کړئ.',
  datenschutz: 'د محرمیت تګلاره (په آلماني)', impressum: 'د خپرونکي مالومات (په آلماني)', fussFrage: 'پوښتنه لرئ؟',
};

TEXTE.ti = {
  s4Titel: "ብተደጋጋሚ ዝሕተቱ ሕቶታት",
  faq: [
    { f: "ክንደይ ይኸፍል?", a: "እቶም ቀዳሞት 3 ደብዳበታት ብነጻ እዮም (ብናይ ምጽባይ ዝርዝር ኮድ 5)። ድሕሪኡ ክሬዲት ትገዝእ፦ 5 መጽናዕቲ ብ2,99 € ወይ 15 ብ6,99 €። ዝኾነ ምዝገባ ወይ ኣካውንት ኣየድልን።" },
    { f: "ኣየኖት ደብዳበታት ከብርህ ይኽእል?", a: "ካብ Jobcenter፣ ቤት ጽሕፈት ወጻእተኛታት፣ ውሕስነት ጡረታ፣ ውሕስነት ጥዕና፣ ስድራቤታዊ ካሳ (Kindergeld)፣ ቤት ጽሕፈት ግብሪ ወይ ቤት ጽሕፈት መቕጻዕቲ ዝመጹ ደብዳበታት — ብሓጺሩ ኩሉ ወግዓዊ ደብዳበ ማለት እዩ።" },
    { f: "ብዛዕባ ዳታይ እንታይ ይኸውን?", a: "ደብዳበታትካ ኣብ ናትካ መሳርሒ ተመስጢሮም ይጸንሑ። ንመጽናዕቲ እቲ ስእሊ ሓንሳብ ብውሑስ መንገዲ ናብ AI ይለኣኽ፣ ኣብኡ ድማ ዝበዝሐ ድሕሪ 30 መዓልቲ ይድምሰስ። ኣካውንት ኣየድልየካን።" },
  ],
  locale: 'ti_ER', navLabel: 'ቋንቋ ምረጽ',
  titel: 'BehördenKlar – ናይ ጀርመን ወግዓዊ ደብዳበ ተረዳእ',
  beschreibung: 'BehördenKlar ናይ ጀርመን ወግዓዊ ደብዳበታት ብቐሊል ቃላት — ብትግርኛ — የብርህ። ስእሊ ውሰድ፣ ተረዳእ፣ ብትኽክል መልስ።',
  ogTitel: 'ካብ ጀርመናዊ ቤት ጽሕፈት ደብዳበ መጺኡካ?',
  ogBeschreibung: 'ስእሊ ውሰድ — BehördenKlar ነቲ ደብዳበ ብቐሊል ቋንቋ፣ ብትግርኛ የብርህ። ናይ ምጽባይ ዝርዝር፦ 5 ነጻ መጽናዕቲ።',
  h1a: 'ካብ ጀርመናዊ ቤት ጽሕፈት ደብዳበ?', h1b: 'ሕጂ ይርዳእ እዩ።',
  intro: 'ናይቲ ደብዳበ ስእሊ ውሰድ። BehördenKlar ብቐሊል ቃላት — <strong>ከምኡውን ብትግርኛ</strong> — የብርሆ። ምስ ኩሎም ግዜታትን ዝርዝር ዕዮን።',
  ctaHero: 'ናብ ናይ ምጽባይ ዝርዝር', stempel: 'ኣብ ቀረባ ግዜ ኣብ iPhone',
  s1Titel: 'ቅድምን ድሕርን', vorherLabel: 'ቅድሚ · ኦሪጅናል ደብዳበ (ብጀርመንኛ)', pfeil: 'ድሕሪ ሓደ ስእሊ',
  nachherLabel: 'ድሕሪ · BehördenKlar ብትግርኛ',
  nachherText: 'ብዘይ ብቑዕ ምኽንያት ናብቲ ቖጸራ እንተዘይከድካ፣ ንሓደ ወርሒ 10 ሚእታዊት ውሑድ ገንዘብ ክትረክብ ኢኻ። ኪድ — ወይ ብግዜኡ ሰርዞ።',
  hinweis: 'እቲ መተግበሪ ደብዳበታት ብቐሊል ጀርመንኛ የብርህን ናብ ልዕሊ 25 ቋንቋታት ይትርጉምን።',
  s2Titel: 'ከመይ ይሰርሕ',
  schritt1T: 'ስእሊ ውሰድ', schritt1B: 'ናይቲ ደብዳበ ስእሊ ውሰድ — ወይ PDF ጸዓን።',
  schritt2T: 'ተረዳእ', schritt2B: 'ብቋንቋኻ ቐሊል ቃላት። ሓደ መብራህቲ ክንደይ ህጹጽ ምዃኑ የርኢ።',
  schritt3T: 'ብትኽክል መልስ', schritt3B: 'ዝርዝር ዕዮ፣ ናይ ግዜ መዘኻኸሪን ድሉው ናይ መልሲ ንድፍን።',
  s3Titel: 'ቅድመ ተበጻሕነት', formularKopf: 'ቅጥዒ F-01 · ናይ ምጽባይ ዝርዝር', formH3: 'ካብ ቀዳሞት ኩን',
  formText: 'እቲ መተግበሪ ኣብ ቀረባ ግዜ ንiPhone ይመጽእ። ተመዝገብ — ምስ ጀመረ <strong>ሓንቲ</strong> ኢመይል ክንልእከልካ ኢና። ዝኾነ መወዓውዒ የለን።',
  bonus: '<strong>ህያብካ፦</strong> ኣብ ክንዲ 3፣ <strong>5 ደብዳበታት ብነጻ</strong>። ነቲ ኮድ ብኢመይል ትረኽቦ።',
  emailPlatzhalter: 'ናትካ ኢመይል ኣድራሻ', ctaForm: 'ኣብ ዝርዝር ተመዝገብ',
  klein: 'ነታ ኣድራሻ ንሓንቲ መልእኽቲ ጥራይ ኢና እንዕቅባ። ኣብ ዝኾነ ግዜ ክትወጽእ ትኽእል።',
  datenschutz: 'ናይ ውልቀ-ሚስጥር ፖሊሲ (ብጀርመንኛ)', impressum: 'ሓበሬታ ኣሕታሚ (ብጀርመንኛ)', fussFrage: 'ሕቶ ኣለካ?',
};

TEXTE.so = {
  s4Titel: "Su’aalaha inta badan la weydiiyo",
  faq: [
    { f: "Intee ayey ku kacaysaa?", a: "3-da warqadood ee ugu horreeya waa bilaash (5 haddii aad haysato koodhka liiska sugitaanka). Kadib waxaad iibsanaysaa rasiid: 5 falanqayn 2,99 € ama 15 falanqayn 6,99 €. Rukun ma jiro, koonto looma baahna." },
    { f: "Warqadaha noocee ah ayuu sharxi karaa?", a: "Warqadaha ka yimid Jobcenter, Xafiiska Ajaanibta, caymiska hawlgabka, caymiska caafimaadka, sanduuqa qoyska (Kindergeld), xafiiska canshuuraha ama xafiiska ganaaxyada — kooban: ku dhawaad warqad kasta oo rasmi ah." },
    { f: "Maxaa ku dhacaya xogtayda?", a: "Warqadahaagu waxay ku hadhayaan qalabkaaga iyagoo sir ah. Falanqaynta awgeed sawirka hal mar ayaa si ammaan ah loogu diraa AI-ga, halkaasna waxaa laga tirtiraa ugu badnaan 30 maalmood gudahood. Koonto uma baahnid." },
  ],
  locale: 'so_SO', navLabel: 'Dooro luqadda',
  titel: 'BehördenKlar – faham warqadda hay’adaha Jarmalka',
  beschreibung: 'BehördenKlar wuxuu ku sharraxaa warqadaha rasmiga ah ee Jarmalka erayo fudud — af-Soomaali. Sawir qaado, faham, si sax ah uga jawaab.',
  ogTitel: 'Ma heshay warqad ka timid hay’ad Jarmal ah?',
  ogBeschreibung: 'Sawir qaado — BehördenKlar wuxuu warqadda ku sharraxaa luqad fudud, af-Soomaali. Liiska sugitaanka: 5 falanqayn oo bilaash ah.',
  h1a: 'Warqad ka timid hay’ad Jarmal ah?', h1b: 'Hadda waa la fahmi karaa.',
  intro: 'Sawir warqadda. BehördenKlar wuxuu ku sharraxaa erayo fudud — <strong>oo af-Soomaali ah</strong>. Waqtiyada oo dhan iyo liis waxa la sameeyo.',
  ctaHero: 'Ku biir liiska sugitaanka', stempel: 'Dhawaan iPhone-ka',
  s1Titel: 'Ka hor iyo ka dib', vorherLabel: 'Ka hor · Warqadda asalka ah (Jarmal)', pfeil: 'hal sawir ka dib',
  nachherLabel: 'Ka dib · BehördenKlar af-Soomaali',
  nachherText: 'Haddii aadan ballanta iman adigoo aan sabab wanaagsan lahayn, hal bil waxaad heli doontaa lacag 10 % ka yar. Tag — ama waqti ku baabi’i.',
  hinweis: 'Abku wuxuu warqadaha ku sharraxaa Jarmal fudud oo u turjumaa in ka badan 25 luqadood.',
  s2Titel: 'Sida ay u shaqeyso',
  schritt1T: 'Sawir qaado', schritt1B: 'Sawir warqadda — ama soo geli PDF.',
  schritt2T: 'Faham', schritt2B: 'Erayo fudud, luqaddaada. Nal ayaa tusaya sida ay u degdeg u tahay.',
  schritt3T: 'Si sax ah uga jawaab', schritt3B: 'Liiska waxa la sameeyo, xusuusin waqti iyo jawaab diyaar ah.',
  s3Titel: 'Gelitaan hore', formularKopf: 'Foomka F-01 · Liiska sugitaanka', formH3: 'Noqo kuwa ugu horreeya',
  formText: 'Abku dhawaan ayuu u imanayaa iPhone. Isdiiwaangeli — waxaan kuu soo diri doonnaa <strong>hal</strong> iimayl marka la bilaabo. Xayeysiin ma jirto.',
  bonus: '<strong>Hadiyaddaada:</strong> falanqee <strong>5 warqadood oo bilaash ah</strong> halkii 3. Koodhka iimayl ayaad ku heli doontaa.',
  emailPlatzhalter: 'Cinwaankaaga iimaylka', ctaForm: 'Isdiiwaangeli liiska',
  klein: 'Cinwaanka waxaan u kaydinaa kaliya fariintan keliya. Waqti kasta waad ka bixi kartaa.',
  datenschutz: 'Siyaasadda sirta (Jarmal)', impressum: 'Macluumaadka daabacaha (Jarmal)', fussFrage: 'Su’aalo ma qabtaa?',
};

TEXTE.zh = {
  s4Titel: "常见问题",
  faq: [
    { f: "收费多少？", a: "前 3 封信免费（用等候名单的兑换码则是 5 封）。之后购买额度：5 次分析 2,99 €，15 次 6,99 €。无订阅，无需注册账号。" },
    { f: "能解释哪些信件？", a: "来自劳动介绍所（Jobcenter）、外管局、养老保险、医疗保险、家庭金库（Kindergeld）、税务局或罚款机关的信件——简而言之，几乎任何官方信件。" },
    { f: "我的数据会怎样？", a: "您的信件以加密方式保存在您自己的设备上。分析时照片会安全地发送给人工智能一次，并最迟在 30 天后在那里删除。您不需要账号。" },
  ],
  locale: 'zh_CN', navLabel: '选择语言',
  titel: 'BehördenKlar – 看懂德国政府部门的信件',
  beschreibung: 'BehördenKlar 用简单的语言解释德国官方信件——中文。拍张照片，看懂内容，正确回复。',
  ogTitel: '收到德国政府部门的信了？',
  ogBeschreibung: '拍张照片——BehördenKlar 用简单的中文解释这封信。等候名单：5 次免费分析。',
  h1a: '收到德国政府部门的信？', h1b: '终于看懂了。',
  intro: '给信件拍张照片。BehördenKlar 会用简单的话——<strong>而且是中文</strong>——向您解释，并列出所有期限和待办事项。',
  ctaHero: '加入等候名单', stempel: '即将登陆 iPhone',
  s1Titel: '前后对比', vorherLabel: '之前 · 原件（德语）', pfeil: '拍一张照片之后',
  nachherLabel: '之后 · BehördenKlar 中文',
  nachherText: '如果您没有正当理由而未去赴约，接下来一个月将少拿 10 % 的钱。请按时前往——或及时取消。',
  hinweis: '应用用简单德语解释信件，并翻译成 25 种以上的语言。',
  s2Titel: '如何使用',
  schritt1T: '拍照', schritt1B: '给信件拍照——或上传 PDF。',
  schritt2T: '看懂', schritt2B: '用您的语言，简单明了。信号灯显示紧急程度。',
  schritt3T: '正确回复', schritt3B: '待办清单、期限提醒，以及一份写好的回信草稿。',
  s3Titel: '抢先体验', formularKopf: '表格 F-01 · 等候名单', formH3: '成为最早的用户',
  formText: '应用即将登陆 iPhone。现在登记——上线时我们只发<strong>一封</strong>邮件。没有广告。',
  bonus: '<strong>您的礼物：</strong>免费分析 <strong>5 封信</strong>，而不是 3 封。兑换码将通过邮件发送。',
  emailPlatzhalter: '您的电子邮箱', ctaForm: '加入等候名单',
  klein: '我们只为这一封邮件保存您的地址。您可以随时退订。',
  datenschutz: '隐私政策（德语）', impressum: '版本说明（德语）', fussFrage: '有疑问？',
};

module.exports = { SPRACHEN, TEXTE };
